const API_BASE = window.VEXA_ACCOUNT_API_BASE || 'https://api-vexaaccount.onrender.com';

const api = (path, options = {}) => fetch(API_BASE + path, { credentials: 'include', ...options, headers: {'Content-Type': 'application/json', ...(options.headers || {})} });
async function json(path, options) { const response = await api(path, options); const data = await response.json().catch(() => ({})); if (!response.ok || data.success === false) throw new Error(data.message || data.error || `Request failed: ${response.status}`); return data; }
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const appRoot = () => document.getElementById('app');
let state = {session:null,profile:null,security:{},prefs:{},credits:{},apps:[],sessions:[],events:[],storage:[],view:'overview'};

function authLayout(title, subtitle, content) { appRoot().innerHTML = `<main class="auth-shell"><section class="auth-card glass"><a class="auth-brand" href="/#/login"><img src="./public/brand.svg" alt="VexaAccount"></a><p class="eyebrow">VEXA ACCOUNT</p><h1>${title}</h1><p class="muted">${subtitle}</p>${content}</section></main>`; }
function authMessage(text, type='') { const el=document.getElementById('authMessage'); if(el){el.textContent=text;el.className=`auth-message ${type}`;} }

function renderLogin(prefill='') {
  authLayout('Welcome back','Sign in once to access all Vexa apps.',`<form id="authForm" class="auth-form"><label>Email<input name="email" type="email" autocomplete="email" inputmode="email" value="${esc(prefill)}" placeholder="you@example.com" required></label><label>Password<input name="password" type="password" autocomplete="current-password" placeholder="Enter your password" minlength="8" required></label><div class="auth-row"><a href="#/forgot-password">Forgot password?</a></div><button class="primary auth-submit" type="submit">Sign in</button><p id="authMessage" class="auth-message" role="alert"></p></form><div class="auth-links">Don't have an account? <a href="#/register">Create one</a></div><div class="auth-security"><b>Security</b><span>Your VexaAccount works across all connected Vexa apps.</span></div>`);
  document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.currentTarget.querySelector('button');b.disabled=true;authMessage('Signing in securely…');try{const d=await json('/api/auth/login',{method:'POST',body:JSON.stringify({email:String(f.get('email')).trim(),password:String(f.get('password'))})});if(d.requiresAuthenticator2fa)return renderTwoFactor('authenticator',d.userId,String(f.get('email')).trim());if(d.requiresEmail2fa)return renderTwoFactor('email',d.userId,String(f.get('email')).trim());location.hash='#/';await load();}catch(err){authMessage(err.message,'error');b.disabled=false;}};
}
function renderRegister(){
  authLayout('Create your VexaAccount','One secure identity for every connected Vexa app.',`<form id="authForm" class="auth-form"><label>Full name<input name="name" autocomplete="name" required placeholder="Your name"></label><label>Email<input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Password<input name="password" type="password" autocomplete="new-password" minlength="8" required placeholder="At least 8 characters"></label><label>Confirm password<input name="confirmPassword" type="password" autocomplete="new-password" minlength="8" required placeholder="Repeat your password"></label><button class="primary auth-submit" type="submit">Create account</button><p id="authMessage" class="auth-message" role="alert"></p></form><div class="auth-links">Already have an account? <a href="#/login">Sign in</a></div>`);
  document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),p=String(f.get('password')),c=String(f.get('confirmPassword')),b=e.currentTarget.querySelector('button');if(p!==c)return authMessage('Passwords do not match.','error');b.disabled=true;authMessage('Creating your account…');try{const d=await json('/api/auth/register',{method:'POST',body:JSON.stringify({name:String(f.get('name')).trim(),email:String(f.get('email')).trim(),password:p})});renderVerifyEmail(String(f.get('email')).trim(),d.message||'Check your email for the verification code.');}catch(err){authMessage(err.message,'error');b.disabled=false;}};
}
function renderVerifyEmail(email,message=''){authLayout('Verify your email','Enter the 6-digit code sent to your email.',`<form id="authForm" class="auth-form"><label>Email<input name="email" type="email" value="${esc(email)}" readonly></label><label>Verification code<input name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="000000"></label><button class="primary auth-submit" type="submit">Verify email</button><p id="authMessage" class="auth-message">${esc(message)}</p></form><div class="auth-links"><a href="#/login">Back to sign in</a></div>`);document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.currentTarget.querySelector('button');b.disabled=true;authMessage('Verifying…');try{await json('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({email:String(f.get('email')),otp:String(f.get('otp')).trim()})});location.hash='#/';await load();}catch(err){authMessage(err.message,'error');b.disabled=false;}};}
function renderTwoFactor(type,userId,email){const label=type==='email'?'Email verification code':'Authenticator code';authLayout('Verify your sign-in',type==='email'?'Enter the code sent to your email.':'Enter the 6-digit code from your authenticator app.',`<form id="authForm" class="auth-form"><label>${label}<input name="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6" minlength="6" required placeholder="000000"></label><button class="primary auth-submit" type="submit">Verify and continue</button><p id="authMessage" class="auth-message" role="alert"></p></form><div class="auth-links"><a href="#/login">Cancel and return to sign in</a></div>`);document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();const otp=String(new FormData(e.currentTarget).get('otp')).trim(),b=e.currentTarget.querySelector('button');b.disabled=true;authMessage('Checking verification code…');try{await json(type==='email'?'/api/auth/verify-email-2fa':'/api/auth/twofa/verify',{method:'POST',body:JSON.stringify(type==='email'?{userId,email,otp}:{userId,token:otp})});location.hash='#/';await load();}catch(err){authMessage(err.message,'error');b.disabled=false;}};}
function renderForgot(){authLayout('Reset your password','Enter your email and we will send a secure reset link.',`<form id="authForm" class="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><button class="primary auth-submit" type="submit">Send reset link</button><p id="authMessage" class="auth-message" role="alert"></p></form><div class="auth-links"><a href="#/login">Back to sign in</a></div>`);document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();const email=String(new FormData(e.currentTarget).get('email')).trim(),b=e.currentTarget.querySelector('button');b.disabled=true;authMessage('Sending reset link…');try{const d=await json('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});authMessage(d.message||'If your email is registered, you will receive a reset link.','success');}catch(err){authMessage(err.message,'error');}finally{b.disabled=false;}};}
function renderReset(token){if(!token)return renderForgot();authLayout('Choose a new password','Create a strong new password for your VexaAccount.',`<form id="authForm" class="auth-form"><label>New password<input name="password" type="password" autocomplete="new-password" minlength="8" required></label><label>Confirm password<input name="confirm" type="password" autocomplete="new-password" minlength="8" required></label><button class="primary auth-submit" type="submit">Reset password</button><p id="authMessage" class="auth-message" role="alert"></p></form>`);document.getElementById('authForm').onsubmit=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),p=String(f.get('password')),c=String(f.get('confirm')),b=e.currentTarget.querySelector('button');if(p!==c)return authMessage('Passwords do not match.','error');b.disabled=true;authMessage('Resetting password…');try{const d=await json('/api/auth/reset-password',{method:'POST',body:JSON.stringify({token,newPassword:p})});authMessage(d.message||'Password reset successfully.','success');setTimeout(()=>location.hash='#/login',1200);}catch(err){authMessage(err.message,'error');b.disabled=false;}};}
function routeAuth(){const raw=location.hash||'';const [route,q='']=raw.split('?');const params=new URLSearchParams(q);if(route==='#/login'||route==='#login')return renderLogin();if(route==='#/register'||route==='#register')return renderRegister();if(route==='#/verify-email')return renderVerifyEmail(params.get('email')||'');if(route==='#/forgot-password')return renderForgot();if(route==='#/reset-password')return renderReset(params.get('token'));return false;}

async function load(){if(routeAuth())return;const session=await json('/api/auth/session');if(!session||!session.success){renderLogin();return;}state.session=session;const results=await Promise.allSettled([json('/api/account/profile'),json('/api/account/security'),json('/api/account/preferences'),json('/api/account/credits'),json('/api/account/storage'),json('/api/account/apps'),json('/api/account/sessions'),json('/api/account/security/events')]);const values=results.map(r=>r.status==='fulfilled'?r.value:{});const [profile,security,prefs,credits,storage,apps,sessions,events]=values;state.profile=profile.user||session.user||{};state.security=security.security||{};state.prefs=prefs.preferences||{};state.credits=credits.balance||{};state.storage=storage.records||[];state.apps=apps.applications||[];state.sessions=sessions.sessions||[];state.events=events.events||[];render();}

function renderLogin(){return renderLoginScreen();}
function renderLoginScreen(){renderLogin();}
function nav(){return [['overview','Overview'],['profile','Profile'],['security','Security'],['apps','Applications'],['sessions','Sessions'],['storage','Cloud storage'],['credits','Credits & coins'],['preferences','Preferences']].map(([id,label])=>`<button class="nav ${state.view===id?'active':''}" data-view="${id}">${label}</button>`).join('');}
function shell(content){const user=state.profile||state.session.user||{};appRoot().innerHTML=`<div class="console"><aside class="sidebar"><div class="brand"><span class="brand-mark">V</span><div><b>VexaAccount</b><small>ACCOUNT CENTER</small></div></div><nav>${nav()}</nav><div class="side-footer"><span class="owner-dot"></span><div><b>${esc(user.name||'Account')}</b><small>${esc(user.email||'')}</small></div></div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">VEXA ACCOUNT</p><h1>Account Center</h1></div><div class="top-actions"><span class="live"><i></i> System online</span><button id="switchAccount" class="secondary">Switch account</button><button id="logout" class="secondary">Sign out</button></div></header><main class="content">${content}</main><nav class="bottom-nav">${nav()}</nav></section></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();});document.getElementById('logout').onclick=logout;document.getElementById('switchAccount').onclick=async()=>{await logout();location.hash='#/login';};}
async function logout(){try{await api('/api/auth/logout',{method:'POST'});}finally{location.hash='#/login';}}
function card(title,body){return `<section class="panel glass"><h2>${title}</h2>${body}</section>`;}
function overview(){const user=state.profile||{};return `<section class="hero glass"><div><p class="eyebrow">CENTRAL IDENTITY PLATFORM</p><h2>Your VexaAccount, connected everywhere.</h2><p>Manage your identity, security, applications, sessions, storage and account preferences from one place.</p></div></section><section class="metrics"><article class="metric glass"><small>Connected applications</small><strong>${state.apps.length}</strong><span>Registered connections</span></article><article class="metric glass"><small>Active sessions</small><strong>${state.sessions.length}</strong><span>Current account sessions</span></article><article class="metric glass"><small>Credit score</small><strong>${esc(state.credits.credit_score??0)}</strong><span>Account balance score</span></article><article class="metric glass"><small>Coins</small><strong>${esc(state.credits.coins??0)}</strong><span>Available coins</span></article></section><section class="grid">${card('Account status',`<p><b>${esc(user.email||'')}</b></p><p class="muted">Status: ${user.is_active?'Active':'Disabled'} · Verified: ${user.is_verified?'Yes':'No'}</p>`)}${card('Recent security activity',state.events.slice(0,6).map(e=>`<article class="row"><div><b>${esc(e.event_type||'Security event')}</b><small>${esc(e.created_at||'')} · ${esc(e.ip_address||'')}</small></div></article>`).join('')||'<p class="muted">No recent security activity.</p>')}</section>`;}
function profile(){const u=state.profile||{};return card('Profile',`<form id="profileForm" class="form-grid"><label>Name<input name="name" value="${esc(u.name)}"></label><label>First name<input name="first_name" value="${esc(u.first_name)}"></label><label>Last name<input name="last_name" value="${esc(u.last_name)}"></label><label>Country<input name="country" value="${esc(u.country)}"></label><label>Gender<input name="gender" value="${esc(u.gender)}"></label><label>Date of birth<input name="dob" type="date" value="${esc(u.dob?String(u.dob).slice(0,10):'')}"></label><button class="primary" type="submit">Save profile</button></form><hr><h3>Change email</h3><form id="emailForm" class="form-grid"><input name="email" type="email" value="${esc(u.email)}" required><input name="password" type="password" placeholder="Current password" required><button class="primary" type="submit">Change email</button></form><hr><h3>Change password</h3><form id="passwordForm" class="form-grid"><input name="currentPassword" type="password" placeholder="Current password" required><input name="newPassword" type="password" placeholder="New password (8+ characters)" minlength="8" required><button class="primary" type="submit">Change password</button></form>`);}
function security(){return card('Security',`<p>Authenticator 2FA: <strong>${state.security.twofa_enabled?'Enabled':'Disabled'}</strong></p><p>Email 2FA: <strong>${state.security.email_2fa_enabled?'Enabled':'Disabled'}</strong></p><p>Security notifications: <strong>${state.security.security_notifications_enabled?'Enabled':'Disabled'}</strong></p><button id="disable2fa" class="secondary">Disable 2FA</button> <button id="disablePasscode" class="secondary">Disable passcode</button><hr><h3>Security events</h3>${state.events.map(e=>`<article class="row"><div><b>${esc(e.event_type||'Event')}</b><small>${esc(e.created_at||'')} · ${esc(e.ip_address||'')}</small></div></article>`).join('')||'<p class="muted">No events.</p>'}`);}
function apps(){return card('Connected applications',state.apps.map(a=>`<article class="app-card"><div class="app-main"><div class="app-icon">${esc((a.display_name||a.name||a.client_id||'A').slice(0,1).toUpperCase())}</div><div><h3>${esc(a.display_name||a.name||a.client_id)}</h3><small>${esc(a.client_id)} · ${esc(a.status||'active')}</small></div></div><button data-revoke="${esc(a.client_id)}" class="danger">Revoke access</button></article>`).join('')||'<p class="muted">No connected applications.</p>');}
function sessions(){return card('Active sessions',state.sessions.map(s=>`<article class="row"><div><b>${esc(s.device||s.user_agent||'Browser session')}</b><small>${esc(s.ip_address||'')} · ${esc(s.last_seen_at||s.created_at||'')}</small></div><button data-session="${esc(s.id)}" class="secondary">Revoke</button></article>`).join('')||'<p class="muted">No active sessions.</p>');}
function storage(){return card('Cloud storage',`<p class="muted">VexaAccount-managed storage records linked to your account.</p>${state.storage.map(r=>`<article class="row"><div><b>${esc(r.display_name||r.storage_key)}</b><small>${esc(r.provider||'')} · ${esc(r.content_type||'')} · ${esc(r.size_bytes||0)} bytes · ${esc(r.status||'')}</small></div><button data-storage="${esc(r.id)}" class="danger">Remove record</button></article>`).join('')||'<p class="muted">No storage records.</p>'}`);}
function credits(){return `<section class="metrics"><article class="metric glass"><small>Credit score</small><strong>${esc(state.credits.credit_score??0)}</strong><span>Current score</span></article><article class="metric glass"><small>Coins</small><strong>${esc(state.credits.coins??0)}</strong><span>Available coins</span></article></section>`;}
function preferences(){const p=state.prefs||{};return card('Preferences',`<form id="prefsForm" class="form-grid"><label>Language<input name="locale" value="${esc(p.locale||'en')}"></label><label>Timezone<input name="timezone" value="${esc(p.timezone||'UTC')}"></label><label><input name="marketing_email_enabled" type="checkbox" ${p.marketing_email_enabled?'checked':''}> Marketing emails</label><label><input name="security_email_enabled" type="checkbox" ${p.security_email_enabled!==0?'checked':''}> Security emails</label><button class="primary" type="submit">Save preferences</button></form><hr><h3>Delete account</h3><p class="muted">This permanently removes your VexaAccount data and revokes active sessions.</p><button id="deleteAccount" class="danger">Delete my account</button>`);}
async function submitForm(e,path,method){e.preventDefault();const b=e.currentTarget.querySelector('button[type="submit"]');if(b)b.disabled=true;try{const data=await json(path,{method,body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});alert(data.message||'Saved successfully');await load();}catch(err){alert(err.message||'Unable to save changes');if(b)b.disabled=false;}}
function bindViewActions(){const pf=document.getElementById('profileForm');if(pf)pf.onsubmit=e=>submitForm(e,'/api/account/profile','PATCH');const ef=document.getElementById('emailForm');if(ef)ef.onsubmit=e=>submitForm(e,'/api/account/email','PATCH');const pw=document.getElementById('passwordForm');if(pw)pw.onsubmit=e=>submitForm(e,'/api/account/password','PATCH');const d2=document.getElementById('disable2fa');if(d2)d2.onclick=async()=>{const password=prompt('Enter your password to disable 2FA');if(!password)return;try{await json('/api/account/security/disable-2fa',{method:'POST',body:JSON.stringify({password})});alert('2FA disabled');await load();}catch(e){alert(e.message)}};const dp=document.getElementById('disablePasscode');if(dp)dp.onclick=async()=>{const password=prompt('Enter your password to disable the passcode');if(!password)return;try{await json('/api/account/security/disable-passcode',{method:'POST',body:JSON.stringify({password})});alert('Passcode disabled');await load();}catch(e){alert(e.message)}};const pf2=document.getElementById('prefsForm');if(pf2)pf2.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/api/account/preferences',{method:'PATCH',body:JSON.stringify({locale:f.get('locale'),timezone:f.get('timezone'),marketing_email_enabled:f.has('marketing_email_enabled'),security_email_enabled:f.has('security_email_enabled')})});alert('Preferences saved');await load();}catch(e){alert(e.message)}};const da=document.getElementById('deleteAccount');if(da)da.onclick=async()=>{const password=prompt('Enter your password to permanently delete your account');if(!password||!confirm('This cannot be undone. Continue?'))return;try{await json('/api/account/account',{method:'DELETE',body:JSON.stringify({password})});location.hash='#/login';await load();}catch(e){alert(e.message)}};}
function render(){const views={overview,profile,security,apps,sessions,storage,credits,preferences};shell(views[state.view]());bindViewActions();document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{if(!confirm('Revoke this application?'))return;try{await json(`/api/account/apps/${encodeURIComponent(b.dataset.revoke)}/consent`,{method:'DELETE'});await load();}catch(e){alert(e.message)}});document.querySelectorAll('[data-session]').forEach(b=>b.onclick=async()=>{try{await json(`/api/account/sessions/${encodeURIComponent(b.dataset.session)}`,{method:'DELETE'});await load();}catch(e){alert(e.message)}});document.querySelectorAll('[data-storage]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this storage record?'))return;try{await json(`/api/account/storage/${encodeURIComponent(b.dataset.storage)}`,{method:'DELETE'});await load();}catch(e){alert(e.message)}});}
window.addEventListener('hashchange',load);
load().catch(error=>{appRoot().innerHTML=`<main class="shell loading-shell"><section class="card glass loading-card"><div class="brand-mark">V</div><p class="eyebrow">VEXA ACCOUNT</p><h1>Unable to load Account Center</h1><p class="muted">${esc(error.message)}</p><button class="primary" onclick="location.reload()">Retry</button></section></main>`;});
