const express = require('express');
const jwt = require('jsonwebtoken');
const { pool } = require('../config/database');
const router = express.Router();
const JWT_SECRET = process.env.JWT_SECRET || 'vexastore_jwt_secret_key';
function requireUser(req,res,next){try{const h=req.get('authorization')||'';if(!h.startsWith('Bearer '))return res.status(401).json({success:false,message:'Authentication required'});const c=jwt.verify(h.slice(7),JWT_SECRET);const userId=c.sub||c.id;if(!userId)return res.status(401).json({success:false,message:'Invalid identity'});req.accountUser={...c,userId};next();}catch{return res.status(401).json({success:false,message:'Invalid or expired session'});}}
router.use(requireUser);
const cols='id,email,name,avatar_url,phone,bio,is_verified,is_active,created_at,twofa_enabled,email_2fa_enabled,first_name,last_name,gender,dob,country';
router.get('/profile',async(req,res,next)=>{try{const[r]=await pool.query(`SELECT ${cols} FROM store_users WHERE id=? AND is_active=1 LIMIT 1`,[req.accountUser.userId]);if(!r.length)return res.status(404).json({success:false,message:'Account not found'});res.json({success:true,profile:r[0]});}catch(e){next(e);}});
router.patch('/profile',async(req,res,next)=>{try{const map={name:'name',phone:'phone',bio:'bio',firstName:'first_name',lastName:'last_name',gender:'gender',dob:'dob',country:'country'};const u=[],v=[];for(const[k,c]of Object.entries(map)){if(req.body[k]!==undefined){let x=req.body[k];if(typeof x==='string')x=x.trim();if(['name','firstName','lastName'].includes(k)&&x==='')return res.status(400).json({success:false,message:`${k} cannot be empty`});u.push(`${c}=?`);v.push(x||null);}}if(!u.length)return res.status(400).json({success:false,message:'No supported fields supplied'});v.push(req.accountUser.userId);await pool.query(`UPDATE store_users SET ${u.join(', ')} WHERE id=? AND is_active=1`,v);const[r]=await pool.query(`SELECT ${cols} FROM store_users WHERE id=? LIMIT 1`,[req.accountUser.userId]);res.json({success:true,message:'Profile updated',profile:r[0]});}catch(e){next(e);}});
router.get('/security',async(req,res,next)=>{try{const[r]=await pool.query('SELECT twofa_enabled,email_2fa_enabled,is_verified,created_at FROM store_users WHERE id=? LIMIT 1',[req.accountUser.userId]);if(!r.length)return res.status(404).json({success:false,message:'Account not found'});res.json({success:true,security:{authenticator_2fa_enabled:Boolean(r[0].twofa_enabled),email_2fa_enabled:Boolean(r[0].email_2fa_enabled),email_verified:Boolean(r[0].is_verified),account_created_at:r[0].created_at}});}catch(e){next(e);}});
router.get('/activity',async(req,res,next)=>{try{const limit=Math.min(Math.max(Number(req.query.limit)||50,1),100);const[r]=await pool.query('SELECT action,ip_address,user_agent,created_at FROM user_activity_logs WHERE user_id=? ORDER BY created_at DESC LIMIT ?',[req.accountUser.userId,limit]);res.json({success:true,events:r});}catch(e){next(e);}});
router.get('/apps',async(req,res,next)=>{try{const[r]=await pool.query('SELECT app_name,app_slug,status,connected_at,last_used_at FROM user_connected_apps WHERE user_id=? ORDER BY connected_at DESC',[req.accountUser.userId]);res.json({success:true,applications:r});}catch(e){next(e);}});
router.delete('/apps/:slug',async(req,res,next)=>{try{const[r]=await pool.query('UPDATE user_connected_apps SET status="disconnected",updated_at=NOW() WHERE user_id=? AND app_slug=? AND status="connected"',[req.accountUser.userId,req.params.slug]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Connected application not found'});res.json({success:true,message:'Application disconnected'});}catch(e){next(e);}});
module.exports=router;