(()=>{'use strict';
const ACCOUNT_API=(window.VEXA_ACCOUNT_API_BASE||'https://api-vexaaccount.onrender.com').replace(/\/$/,'');
const MAIL_API=(window.VEXAMAIL_API_BASE||'').replace(/\/$/,'');
const token=()=>window.vexaMailToken||localStorage.getItem('vexaaccount_access_token')||sessionStorage.getItem('vexaaccount_access_token');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function accountSession(){const h={Accept:'application/json'};const t=token();if(t)h.Authorization='Bearer '+t;const r=await fetch(ACCOUNT_API+'/api/auth/session',{credentials:'include',headers:h});const d=await r.json().catch(()=>({}));if(r.status===401||!d?.success)return null;return d.user||null}
async function mailRequest(path,options={}){if(!MAIL_API)throw Error('VexaMail API is not configured yet. Set VEXAMAIL_API_BASE to the deployed VexaMail Web Service.');const h=new Headers(options.headers||{});h.set('Content-Type','application/json');const t=token();if(t)h.set('Authorization','Bearer '+t);const r=await fetch(MAIL_API+path,{...options,headers:h,credentials:'include'});const d=await r.json().catch(()=>({message:'Invalid server response'}));if(r.status===401){location.href=ACCOUNT_API+'/';throw Error('Your VexaAccount session has expired.')}if(!r.ok||d.success===false)throw Error(d.message||('Mail request failed ('+r.status+')'));return d}
const state={user:null,folder:'inbox',messages:[],loading:false};
const app=()=>document.querySelector('#app');
function shell(){app().innerHTML=`<div class="layout glass"><aside class="sidebar"><div class="brand"><div class="brand-icon">V</div><div><strong>VexaMail</strong><small>SECURE WEBMAIL</small></div></div><button class="compose" id="compose">＋ Compose</button><nav class="nav"><button class="active" data-folder="inbox">Inbox</button><button data-folder="starred">★ Starred</button><button data-folder="sent">↗ Sent</button><button data-folder="drafts">◧ Drafts</button><button data-folder="trash">⌫ Trash</button><button data-folder="spam">⚠ Spam</button></nav><div class="account"><b>${esc(state.user?.name||state.user?.email||'VexaAccount user')}</b><div class="muted">${esc(state.user?.email||'')}</div></div></aside><section class="workspace"><header class="topbar"><div class="search"><input id="search" placeholder="Search mail…"></div><div class="actions"><button class="icon-btn" id="refresh" title="Refresh">↻</button><button class="icon-btn" id="logout" title="Sign out">⇥</button></div></header><main class="content"><div class="toolbar"><div><h1 id="folderTitle">Inbox</h1><span class="count" id="count"></span></div></div><section id="mailList" class="mail-list"></section></main></section></div><nav class="mobile-nav"><button class="active" data-folder="inbox">Inbox</button><button data-folder="starred">★ Starred</button><button data-folder="sent">Sent</button><button id="mobileCompose">＋ Compose</button></nav>`;document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{state.folder=b.dataset.folder;document.querySelectorAll('[data-folder]').forEach(x=>x.classList.toggle('active',x.dataset.folder===state.folder));load()});document.querySelector('#compose').onclick=compose;document.querySelector('#mobileCompose').onclick=compose;document.querySelector('#refresh').onclick=load;document.querySelector('#logout').onclick=logout;document.querySelector('#search').oninput=e=>render(e.target.value);load()}
function render(query=''){const list=document.querySelector('#mailList');let rows=state.messages.filter(m=>!query||[m.subject,m.from,m.to,m.preview,m.body].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));document.querySelector('#count').textContent=rows.length+' message'+(rows.length===1?'':'s');if(!rows.length){list.innerHTML='<div class="empty">No messages here yet.</div>';return}list.innerHTML=rows.map(m=>`<article class="mail-row ${m.unread?'unread':''}" data-id="${esc(m.id)}"><button class="star" title="Star">${m.starred?'★':'☆'}</button><div class="sender">${esc(m.from||m.to||'Unknown')}</div><div><div class="subject">${esc(m.subject||'(no subject)')}</div><div class="preview">${esc(m.preview||m.body||'')}</div></div><div class="date">${esc(m.date||'')}</div></article>`).join('');list.querySelectorAll('.mail-row').forEach(row=>row.onclick=()=>openMessage(row.dataset.id))}
async function load(){if(state.loading)return;state.loading=true;const list=document.querySelector('#mailList');if(list)list.innerHTML='<div class="empty">Syncing mailbox…</div>';try{const d=await mailRequest('/api/mail/messages?folder='+encodeURIComponent(state.folder));state.messages=Array.isArray(d.messages)?d.messages:[];document.querySelector('#folderTitle').textContent=state.folder[0].toUpperCase()+state.folder.slice(1);render()}catch(e){if(list)list.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}finally{state.loading=false}}
function modal(html){const x=document.createElement('div');x.className='overlay';x.innerHTML='<section class="modal glass">'+html+'</section>';document.body.appendChild(x);return x}
function compose(){const x=modal('<h2>New message</h2><form id="composeForm"><label class="field">To<input name="to" type="email" required></label><label class="field">Subject<input name="subject"></label><label class="field">Message<textarea name="body" required></textarea></label><div class="modal-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Send message</button></div></form>');x.querySelector('#cancel').onclick=()=>x.remove();x.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const b=e.currentTarget.querySelector('.primary');b.disabled=true;b.textContent='Sending…';try{await mailRequest('/api/mail/send',{method:'POST',body:JSON.stringify({to:String(f.get('to')).trim(),subject:String(f.get('subject')||''),body:String(f.get('body'))})});x.remove();await load()}catch(err){alert(err.message);b.disabled=false;b.textContent='Send message'}}}
async function openMessage(id){const m=state.messages.find(x=>String(x.id)===String(id));if(!m)return;const x=modal('<h2>'+esc(m.subject||'(no subject)')+'</h2><p class="muted">From: '+esc(m.from||'')+'<br>To: '+esc(m.to||'')+'</p><hr><div style="white-space:pre-wrap;line-height:1.7">'+esc(m.body||m.preview||'')+'</div><div class="modal-actions"><button class="secondary" id="close">Close</button></div>');x.querySelector('#close').onclick=()=>x.remove();try{if(!m.read&&m.id)await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/read',{method:'POST'});m.read=true;render()}catch{}}
async function logout(){try{if(MAIL_API)await mailRequest('/api/mail/logout',{method:'POST'})}catch{}localStorage.removeItem('vexaaccount_access_token');sessionStorage.removeItem('vexaaccount_access_token');location.href=ACCOUNT_API+'/#/login'}
async function boot(){state.user=await accountSession();if(!state.user){location.href=ACCOUNT_API+'/#/login';return}shell()}
boot().catch(e=>{app().innerHTML='<div class="loading glass"><div class="logo">!</div><p>VexaMail could not start</p><span>'+esc(e.message)+'</span></div>'});
})();