(()=>{'use strict';
const ACCOUNT_API=(window.VEXA_ACCOUNT_API_BASE||'https://api-vexaaccount.onrender.com').replace(/\/$/,'');
const MAIL_API=(window.VEXAMAIL_API_BASE||ACCOUNT_API).replace(/\/$/,'');
const token=()=>window.vexaMailToken||localStorage.getItem('vexaaccount_access_token')||sessionStorage.getItem('vexaaccount_access_token');
const refreshToken=()=>localStorage.getItem('vexamail_refresh_token');
const saveTokens=d=>{if(d?.access_token){window.vexaMailToken=d.access_token;localStorage.setItem('vexaaccount_access_token',d.access_token)}if(d?.refresh_token)localStorage.setItem('vexamail_refresh_token',d.refresh_token)};
const randomText=n=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const base64url=bytes=>{let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
async function startSso(){const state=randomText(24),verifier=randomText(48);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=base64url(new Uint8Array(digest));sessionStorage.setItem('vexamail_sso_state',state);sessionStorage.setItem('vexamail_sso_verifier',verifier);const u=new URL(ACCOUNT_API+'/api/sso/authorize');u.searchParams.set('client_id','vexamail-user');u.searchParams.set('redirect_uri',location.origin+'/');u.searchParams.set('response_type','code');u.searchParams.set('scope','openid profile email account session');u.searchParams.set('state',state);u.searchParams.set('code_challenge',challenge);u.searchParams.set('code_challenge_method','S256');location.href=u.toString()}
async function finishSso(){const p=new URLSearchParams(location.search),code=p.get('code'),state=p.get('state');if(!code)return false;if(!state||state!==sessionStorage.getItem('vexamail_sso_state'))throw Error('Invalid VexaMail SSO state');const verifier=sessionStorage.getItem('vexamail_sso_verifier');if(!verifier)throw Error('VexaMail SSO verification state is missing');const body=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:location.origin+'/',client_id:'vexamail-user',client_secret:'PUBLIC',code_verifier:verifier});const r=await fetch(ACCOUNT_API+'/api/sso/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Error(d.message||'VexaAccount SSO token exchange failed');saveTokens(d);sessionStorage.removeItem('vexamail_sso_state');sessionStorage.removeItem('vexamail_sso_verifier');history.replaceState({},document.title,location.pathname+location.hash);return true}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function accountSession(){const t=token();if(t){const r=await fetch(ACCOUNT_API+'/api/sso/userinfo',{headers:{Authorization:'Bearer '+t,Accept:'application/json'}});if(r.ok){const d=await r.json();return {id:d.sub,email:d.email,name:d.name||d.email}}}const rt=refreshToken();if(rt){const r=await fetch(ACCOUNT_API+'/api/sso/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:rt,client_id:'vexamail-user',client_secret:'PUBLIC'})});const d=await r.json().catch(()=>({}));if(r.ok&&d.access_token){saveTokens(d);const u=await fetch(ACCOUNT_API+'/api/sso/userinfo',{headers:{Authorization:'Bearer '+d.access_token,Accept:'application/json'}});if(u.ok){const x=await u.json();return {id:x.sub,email:x.email,name:x.name||x.email}}}}return null}
async function mailRequest(path,options={}){if(!MAIL_API)throw Error('VexaMail API is not configured yet. Set VEXAMAIL_API_BASE to the deployed VexaMail Web Service.');const h=new Headers(options.headers||{});h.set('Content-Type','application/json');const t=token();if(t)h.set('Authorization','Bearer '+t);const r=await fetch(MAIL_API+path,{...options,headers:h,credentials:'include'});const d=await r.json().catch(()=>({message:'Invalid server response'}));if(r.status===401){location.href=ACCOUNT_API+'/';throw Error('Your VexaAccount session has expired.')}if(!r.ok||d.success===false)throw Error(d.message||('Mail request failed ('+r.status+')'));return d}
const state={user:null,folder:'inbox',messages:[],loading:false};
const app=()=>document.querySelector('#app');
function shell(){app().innerHTML=`<div class="layout glass"><aside class="sidebar"><div class="brand"><div class="brand-icon">V</div><div><strong>VexaMail</strong><small>SECURE WEBMAIL</small></div></div><button class="compose" id="compose">＋ Compose</button><nav class="nav"><button class="active" data-folder="inbox">Inbox</button><button data-folder="starred">★ Starred</button><button data-folder="sent">↗ Sent</button><button data-folder="drafts">◧ Drafts</button><button data-folder="trash">⌫ Trash</button><button data-folder="spam">⚠ Spam</button></nav><div class="account"><b>${esc(state.user?.name||state.user?.email||'VexaAccount user')}</b><div class="muted">${esc(state.user?.email||'')}</div></div></aside><section class="workspace"><header class="topbar"><div class="search"><input id="search" placeholder="Search mail…"></div><div class="actions"><button class="icon-btn" id="refresh" title="Refresh">↻</button><button class="icon-btn" id="logout" title="Sign out">⇥</button></div></header><main class="content"><div class="toolbar"><div><h1 id="folderTitle">Inbox</h1><span class="count" id="count"></span></div></div><section id="mailList" class="mail-list"></section></main></section></div><nav class="mobile-nav"><button class="active" data-folder="inbox">Inbox</button><button data-folder="starred">★ Starred</button><button data-folder="sent">Sent</button><button id="mobileCompose">＋ Compose</button></nav>`;document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{state.folder=b.dataset.folder;document.querySelectorAll('[data-folder]').forEach(x=>x.classList.toggle('active',x.dataset.folder===state.folder));load()});document.querySelector('#compose').onclick=compose;document.querySelector('#mobileCompose').onclick=compose;document.querySelector('#refresh').onclick=load;document.querySelector('#logout').onclick=logout;document.querySelector('#search').oninput=e=>render(e.target.value);load()}
function render(query=''){const list=document.querySelector('#mailList');let rows=state.messages.filter(m=>!query||[m.subject,m.from,m.to,m.preview,m.body].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));document.querySelector('#count').textContent=rows.length+' message'+(rows.length===1?'':'s');if(!rows.length){list.innerHTML='<div class="empty">No messages here yet.</div>';return}list.innerHTML=rows.map(m=>`<article class="mail-row ${m.unread?'unread':''}" data-id="${esc(m.id)}"><button class="star" title="Star">${m.starred?'★':'☆'}</button><div class="sender">${esc(m.from||m.to||'Unknown')}</div><div><div class="subject">${esc(m.subject||'(no subject)')}</div><div class="preview">${esc(m.preview||m.body||'')}</div></div><div class="date">${esc(m.date||'')}</div></article>`).join('');list.querySelectorAll('.mail-row').forEach(row=>{row.onclick=()=>openMessage(row.dataset.id);const star=row.querySelector('.star');if(star)star.onclick=async e=>{e.stopPropagation();const m=state.messages.find(x=>String(x.id)===String(row.dataset.id));if(!m)return;try{await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/star',{method:'PATCH',body:JSON.stringify({starred:!m.starred})});m.starred=!m.starred;render(query)}catch(err){alert(err.message)}}})}
async function load(){if(state.loading)return;state.loading=true;const list=document.querySelector('#mailList');if(list)list.innerHTML='<div class="empty">Syncing mailbox…</div>';try{const d=await mailRequest('/api/mail/messages?folder='+encodeURIComponent(state.folder));state.messages=Array.isArray(d.messages)?d.messages:[];document.querySelector('#folderTitle').textContent=state.folder[0].toUpperCase()+state.folder.slice(1);render()}catch(e){if(list)list.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}finally{state.loading=false}}
function modal(html){const x=document.createElement('div');x.className='overlay';x.innerHTML='<section class="modal glass">'+html+'</section>';document.body.appendChild(x);return x}
function compose(){const x=modal('<h2>New message</h2><form id="composeForm"><label class="field">To<input name="to" type="email" required></label><label class="field">Subject<input name="subject"></label><label class="field">Message<textarea name="body" required></textarea></label><div class="modal-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Send message</button></div></form>');x.querySelector('#cancel').onclick=()=>x.remove();x.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const b=e.currentTarget.querySelector('.primary');b.disabled=true;b.textContent='Sending…';try{await mailRequest('/api/mail/send',{method:'POST',body:JSON.stringify({to:String(f.get('to')).trim(),subject:String(f.get('subject')||''),body:String(f.get('body'))})});x.remove();await load()}catch(err){alert(err.message);b.disabled=false;b.textContent='Send message'}}}
async function openMessage(id){const m=state.messages.find(x=>String(x.id)===String(id));if(!m)return;const x=modal('<h2>'+esc(m.subject||'(no subject)')+'</h2><p class="muted">From: '+esc(m.from||'')+'<br>To: '+esc(m.to||'')+'</p><hr><div style="white-space:pre-wrap;line-height:1.7">'+esc(m.body||m.preview||'')+'</div><div class="modal-actions"><button class="secondary" id="toggleRead">'+(m.read?'Mark unread':'Mark read')+'</button><button class="secondary" id="toggleStar">'+(m.starred?'Unstar':'Star')+'</button><button class="secondary" id="trash">Trash</button><button class="secondary" id="spam">Spam</button><button class="secondary" id="close">Close</button></div>');x.querySelector('#close').onclick=()=>x.remove();x.querySelector('#toggleRead').onclick=async()=>{try{await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/read',{method:'PATCH',body:JSON.stringify({read:!m.read})});m.read=!m.read;x.remove();render()}catch(err){alert(err.message)}};x.querySelector('#toggleStar').onclick=async()=>{try{await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/star',{method:'PATCH',body:JSON.stringify({starred:!m.starred})});m.starred=!m.starred;x.remove();render()}catch(err){alert(err.message)}};x.querySelector('#trash').onclick=async()=>{try{await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/trash',{method:'PATCH',body:JSON.stringify({trash:true})});x.remove();await load()}catch(err){alert(err.message)}};x.querySelector('#spam').onclick=async()=>{try{await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/spam',{method:'PATCH',body:JSON.stringify({spam:true})});x.remove();await load()}catch(err){alert(err.message)}};try{if(!m.read&&m.id)await mailRequest('/api/mail/messages/'+encodeURIComponent(m.id)+'/read',{method:'PATCH',body:JSON.stringify({read:true})});m.read=true;render()}catch{}}
async function logout(){const rt=refreshToken();try{if(rt)await fetch(ACCOUNT_API+'/api/sso/logout',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({refresh_token:rt})})}catch{}localStorage.removeItem('vexaaccount_access_token');localStorage.removeItem('vexamail_refresh_token');sessionStorage.removeItem('vexaaccount_access_token');window.vexaMailToken=null;location.href=ACCOUNT_API+'/#/login'}
async function boot(){try{await finishSso()}catch(e){app().innerHTML='<div class="loading glass"><div class="logo">!</div><p>VexaMail sign-in failed</p><span>'+esc(e.message)+'</span><button class="primary" id="retry">Sign in with VexaAccount</button></div>';document.querySelector('#retry').onclick=startSso;return}state.user=await accountSession();if(!state.user){await startSso();return}shell()}
boot().catch(e=>{app().innerHTML='<div class="loading glass"><div class="logo">!</div><p>VexaMail could not start</p><span>'+esc(e.message)+'</span></div>'});
})();