const crypto = require('crypto');

const SAFE_NAME = /^[A-Za-z0-9._-]{1,100}$/;
const URL_RE = /^https:\/\/[^\s]+$/i;

function clean(v, max = 500) { return String(v ?? '').trim().slice(0, max); }
function validateInput(body = {}) {
  const appKey = clean(body.applicationKey, 100);
  const displayName = clean(body.displayName || appKey, 160);
  const backendUrl = clean(body.backendUrl, 500).replace(/\/$/, '');
  const userUrl = clean(body.frontendUserUrl, 500).replace(/\/$/, '');
  const adminUrl = clean(body.frontendAdminUrl, 500).replace(/\/$/, '');
  if (!SAFE_NAME.test(appKey)) throw Object.assign(new Error('applicationKey must contain only letters, numbers, dot, underscore or hyphen'), { status: 400 });
  for (const [name, value] of [['backendUrl', backendUrl], ['frontendUserUrl', userUrl], ['frontendAdminUrl', adminUrl]]) {
    if (!URL_RE.test(value)) throw Object.assign(new Error(`${name} must be an HTTPS URL`), { status: 400 });
  }
  return { appKey, displayName, backendUrl, frontendUserUrl: userUrl, frontendAdminUrl: adminUrl, framework: clean(body.framework, 80) || 'javascript', language: clean(body.language, 40) || 'javascript' };
}

function envExample(c) {
  return `# Generated by VexaAccount Owner SSO Application Kit\n# Never commit real secrets. Put the application's own JWT secret in its deployment secret manager.\nVEXA_ACCOUNT_ISSUER=https://api-vexaaccount.onrender.com\nVEXA_ACCOUNT_FRONTEND=https://vexaaccount-management.onrender.com\nVEXA_SSO_CLIENT_ID=<register-in-VexaAccount-Owner-SSO>\nVEXA_SSO_CLIENT_SECRET=<store-only-in-server-secret-manager>\nJWT_SECRET=<your-${c.appKey}-own-jwt-secret>\nVEXA_BACKEND_URL=${c.backendUrl}\nVEXA_FRONTEND_USER_URL=${c.frontendUserUrl}\nVEXA_FRONTEND_ADMIN_URL=${c.frontendAdminUrl}\n`;
}

function backendSso() { return `const crypto = require('crypto');\nconst axios = require('axios');\nconst VEXA_ISSUER = String(process.env.VEXA_ACCOUNT_ISSUER || 'https://api-vexaaccount.onrender.com').replace(/\\/$/, '');\nconst CLIENT_ID = String(process.env.VEXA_SSO_CLIENT_ID || '').trim();\nconst CLIENT_SECRET = String(process.env.VEXA_SSO_CLIENT_SECRET || '').trim();\nconst REDIRECT_URI = String(process.env.VEXA_SSO_REDIRECT_URI || '').trim();\nif (!CLIENT_ID || !CLIENT_SECRET || !REDIRECT_URI) throw new Error('VexaAccount SSO server configuration is incomplete');\nfunction challenge(v) { return crypto.createHash('sha256').update(v).digest('base64url'); }\nfunction authorizationUrl(state, verifier, loginHint = '', prompt = '') {\n  const q = new URLSearchParams({ client_id: CLIENT_ID, redirect_uri: REDIRECT_URI, response_type: 'code', scope: 'openid profile email account session applications notifications', state, code_challenge: challenge(verifier), code_challenge_method: 'S256' });\n  if (loginHint) q.set('login_hint', loginHint); if (prompt) q.set('prompt', prompt);\n  return VEXA_ISSUER + '/api/sso/authorize?' + q.toString();\n}\nasync function exchangeCode(code, verifier) { const r = await axios.post(VEXA_ISSUER + '/api/sso/token', new URLSearchParams({ grant_type:'authorization_code', code, redirect_uri:REDIRECT_URI, client_id:CLIENT_ID, client_secret:CLIENT_SECRET, code_verifier:verifier }), { headers:{'content-type':'application/x-www-form-urlencoded'}, timeout:15000 }); return r.data; }\nasync function userinfo(accessToken) { const r = await axios.get(VEXA_ISSUER + '/api/sso/userinfo', { headers:{Authorization:'Bearer '+accessToken}, timeout:10000 }); return r.data; }\nmodule.exports = { authorizationUrl, exchangeCode, userinfo };\n`; }

function backendRoute() { return `// Mount this router under /api/auth/vexaaccount. Keep the client secret server-side.\nconst express = require('express');\nconst crypto = require('crypto');\nconst { authorizationUrl, exchangeCode, userinfo } = require('./vexaaccount-sso');\nconst router = express.Router();\nconst pending = new Map();\nrouter.get('/login', (req,res) => { const state=crypto.randomBytes(32).toString('base64url'), verifier=crypto.randomBytes(32).toString('base64url'); pending.set(state,{verifier,expires:Date.now()+10*60*1000}); res.redirect(302, authorizationUrl(state,verifier,String(req.query.login_hint||''),'login')); });\nrouter.get('/callback', async (req,res,next) => { try { const state=String(req.query.state||''), code=String(req.query.code||''); const tx=pending.get(state); pending.delete(state); if(!tx || tx.expires<Date.now() || !code) return res.status(400).json({error:'INVALID_SSO_TRANSACTION'}); const tokens=await exchangeCode(code,tx.verifier); const identity=await userinfo(tokens.access_token); req.vexaIdentity=identity; res.json({success:true,identity}); } catch(e){next(e);} });\nmodule.exports = router;\n`; }

function frontendUser() { return `// VexaAccount user-side adapter. Do not put the client secret in this file.\nexport function startVexaAccountLogin({ backendUrl, loginHint = '', prompt = 'login' } = {}) { const base=String(backendUrl||'').replace(/\\/$/,''); const q=new URLSearchParams(); if(loginHint) q.set('login_hint',loginHint); if(prompt) q.set('prompt',prompt); window.location.assign(base+'/api/auth/vexaaccount/login?'+q.toString()); }\nexport function manageVexaAccount(url='https://vexaaccount-management.onrender.com') { window.location.assign(url); }\n` }
function frontendAdmin() { return `// VexaAccount admin-side integration metadata. Never expose VEXA_SSO_CLIENT_SECRET or JWT_SECRET here.\nexport const vexaAccountIntegration = { issuer: 'https://api-vexaaccount.onrender.com', scopes: ['openid','profile','email','account','session','applications','notifications'] };\nexport function openVexaAccountAdmin(url='https://vexaaccount-management.onrender.com') { window.open(url,'_blank','noopener,noreferrer'); }\n`; }
function readme(c) { return `# ${c.displayName} — VexaAccount SSO Kit\n\nGenerated by VexaAccount Owner SSO Application Kit.\n\n## Security\n- VexaAccount is the identity provider.\n- Passwords stay on the VexaAccount origin.\n- Use Authorization Code + S256 PKCE.\n- Keep the client secret and this application's own JWT secret only in the backend secret manager.\n- Never copy Telegram/third-party browser cookies or tokens.\n\n## Application endpoints\n- Backend: ${c.backendUrl}\n- User frontend: ${c.frontendUserUrl}\n- Admin frontend: ${c.frontendAdminUrl}\n\nInstall the generated backend adapter and route, register the application's redirect URI in VexaAccount Owner SSO Control, then configure the generated environment variables.\n`; }

function generate(body) { const c=validateInput(body); return { manifest:{generatorVersion:'1.0.0',application:c,security:['authorization_code_pkce_s256','server_side_client_secret','no_third_party_cookie_copy'],generatedAt:new Date().toISOString()}, files:[
 {path:'backend/.env.vexaaccount.example',code:envExample(c)},
 {path:'backend/src/integrations/vexaaccount-sso.js',code:backendSso()},
 {path:'backend/src/routes/vexaaccount-auth.js',code:backendRoute()},
 {path:'frontend-user/src/integrations/vexaaccount.js',code:frontendUser()},
 {path:'frontend-admin/src/integrations/vexaaccount.js',code:frontendAdmin()},
 {path:'VEXAACCOUNT_SSO_INTEGRATION.md',code:readme(c)}] }; }
module.exports = { generate, validateInput };
