const axios=require('axios');
const crypto=require('crypto');
const API=String(process.env.GITHUB_API_URL||'https://api.github.com').replace(/\/$/,'');
const TOKEN=String(process.env.GITHUB_SSO_ANALYZE_TOKEN||process.env.GITHUB_SSO_DEPLOY_TOKEN||'').trim();
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function repoName(v){const r=String(v||'').trim().replace(/^https?:\/\/github\.com\//i,'').replace(/\/$/,'').replace(/\.git$/i,'');if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(r))fail('repository must use owner/repository format');return r;}
function headers(){if(!TOKEN)fail('GitHub source analysis is not configured. Set GITHUB_SSO_ANALYZE_TOKEN on the VexaAccount backend.',503);return{Authorization:`Bearer ${TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'VexaAccount-Target-Replacement-Generator'};}
async function get(repo,path,ref){try{return(await axios.get(`${API}/repos/${repo}/contents/${path}?ref=${encodeURIComponent(ref)}`,{headers:headers(),timeout:15000,maxContentLength:2000000})).data;}catch(e){throw Object.assign(new Error(`GitHub target source read: ${e.response?.data?.message||e.message}`),{status:e.response?.status||502});}}
function decode(v){return Buffer.from(String(v||''),'base64').toString('utf8');}
function sha(text){return crypto.createHash('sha256').update(text,'utf8').digest('hex');}
function injectBackendEntry(text){if(/vexaaccount-auth/i.test(text))return {content:text,changed:false,reason:'VexaAccount route already referenced'};const requireLine="const vexaAccountAuth = require('./routes/vexaaccount-auth');";const mountLine="app.use('/api/auth/vexaaccount', vexaAccountAuth);";let out=text;const importAt=/((?:const|let|var)\s+app\s*=\s*(?:express\(\)|[^;]+);)/.exec(out);if(importAt)out=out.slice(0,importAt.index+importAt[0].length)+'\n'+requireLine+out.slice(importAt.index+importAt[0].length);const listen=/^\s*(?:app|server)\.listen\s*\(/m;const m=listen.exec(out);if(!m)return {content:text,changed:false,reason:'No safe app.listen anchor found'};out=out.slice(0,m.index)+mountLine+'\n'+out.slice(m.index);return {content:out,changed:true,reason:'Mounted generated VexaAccount authentication router before server startup'};}
function injectFrontend(text){if(/startVexaAccountLogin|vexaaccount-management\.onrender\.com/i.test(text))return {content:text,changed:false,reason:'VexaAccount frontend bridge already referenced'};const snippet="\n// VexaAccount SSO integration — generated bridge. Secrets remain server-side.\nwindow.startVexaAccountLogin = function(backendUrl, loginHint) { const base=String(backendUrl||'').replace(/\\/$/,''); const q=new URLSearchParams(); if(loginHint) q.set('login_hint',loginHint); window.location.assign(base+'/api/auth/vexaaccount/login?'+q.toString()); };\nwindow.manageVexaAccount = function(url) { window.location.assign(url || 'https://vexaaccount-management.onrender.com'); };\n";return {content:text+snippet,changed:true,reason:'Preserved existing frontend source and appended a browser-safe SSO bridge without changing the existing theme/layout'};}
function transform(path,text,stack){const p=path.toLowerCase();if((stack.backend==='Node.js/Express'||stack.backend==='Node.js/NestJS')&&/(^|\/)(server|app|index|main|bootstrap)\.(js|mjs|cjs|ts|tsx)$/i.test(path))return injectBackendEntry(text);if(/(^|\/)(app|main|index)\.(jsx?|tsx?)$/i.test(path)&&/(React|Next\.js|Vue|Svelte)/i.test(stack.frontend||''))return injectFrontend(text);return {content:text,changed:false,reason:'No deterministic whole-file transformation anchor; generated additive files should be installed instead of guessing application-specific auth semantics'};}
async function generateTarget({repository,branch,reviewedFiles=[],stack={}}={}){const repo=repoName(repository);if(!Array.isArray(reviewedFiles)||!reviewedFiles.length)fail('A signed source plan with reviewedFiles is required');const files=[];for(const rf of reviewedFiles.slice(0,30)){const path=String(rf.path||'');const d=await get(repo,path,branch);const original=decode(d.content);if(d.sha!==rf.blobSha)fail(`Target file changed since source review: ${path}`,409);const t=transform(path,original,stack);files.push({path,originalBlobSha:d.sha,originalSha256:sha(original),replacement:t.content,replacementSha256:sha(t.content),changed:t.changed,reason:t.reason,bytes:Buffer.byteLength(t.content,'utf8')});}return{success:true,mode:'target-specific',repository:repo,branch,stack,files,summary:{reviewed:files.length,replacementCandidates:files.filter(f=>f.changed).length,unchangedReviewFiles:files.filter(f=>!f.changed).length},policy:'Generated replacement files preserve the exact reviewed source and apply only deterministic anchors. Files without a deterministic safe anchor are returned unchanged and must use the additive integration files or explicit Owner review; the system never invents application-specific authentication semantics.'};}
module.exports={generateTarget};
