const crypto = require('crypto');

const SAFE_NAME = /^[A-Za-z0-9._-]{1,100}$/;
const URL_RE = /^https:\/\/[^\s]+$/i;
const SUPPORTED_BACKEND = 'Node.js/Express';

function clean(v, max = 500) { return String(v ?? '').trim().slice(0, max); }
function safeDiagnostic(value) {
  const s = String(value ?? '');
  return { type: typeof value, length: s.length, trimmedLength: s.trim().length, codePoints: Array.from(s).map(ch => ch.codePointAt(0)) };
}
function validateInput(body = {}) {
  const appKey = clean(body.applicationKey, 100);
  const displayName = clean(body.displayName || appKey, 160);
  const backendUrl = clean(body.backendUrl, 500).replace(/\/$/, '');
  const userUrl = clean(body.frontendUserUrl, 500).replace(/\/$/, '');
  const adminUrl = clean(body.frontendAdminUrl, 500).replace(/\/$/, '');
  const hasAdminFrontend = body.hasAdminFrontend === undefined
    ? Boolean(adminUrl)
    : body.hasAdminFrontend === true || String(body.hasAdminFrontend).toLowerCase() === 'true';
  const framework = clean(body.framework, 80);
  const language = clean(body.language, 40) || 'javascript';
  const safeNameValid = SAFE_NAME.test(appKey);
  if (!safeNameValid) {
    console.error('SSO kit applicationKey validation failed', { raw: safeDiagnostic(body.applicationKey), cleaned: safeDiagnostic(appKey), regexPassed: safeNameValid });
    throw Object.assign(new Error('applicationKey must contain only letters, numbers, dot, underscore or hyphen'), { status: 400 });
  }
  for (const [name, value] of [['backendUrl', backendUrl], ['frontendUserUrl', userUrl]]) {
    if (!URL_RE.test(value)) throw Object.assign(new Error(`${name} must be an HTTPS URL`), { status: 400 });
  }
  if (hasAdminFrontend && !URL_RE.test(adminUrl)) {
    throw Object.assign(new Error('frontendAdminUrl must be an HTTPS URL when an Admin Frontend is enabled'), { status: 400 });
  }
  if (framework !== SUPPORTED_BACKEND) throw Object.assign(new Error(`The current complete source generator supports ${SUPPORTED_BACKEND} only. Detected target backend: ${framework || 'unknown'}. Use the read-only analyzer/planner for unsupported stacks instead of installing an incompatible Express integration.`), { status: 409 });
  return { appKey, displayName, backendUrl, frontendUserUrl: userUrl, frontendAdminUrl: hasAdminFrontend ? adminUrl : null, hasAdminFrontend, framework, language };
}

function envExample(c) {
  const redirect = `${c.backendUrl}/api/auth/vexaaccount/callback`;
  const adminLine = c.hasAdminFrontend ? `VEXA_FRONTEND_ADMIN_URL=${c.frontendAdminUrl}\n` : '# No admin frontend is configured for this application.\n';
  return `# Generated by VexaAccount Owner SSO Application Kit\n# Never commit real secrets. Put secrets in the application's deployment secret manager.\nVEXA_ACCOUNT_ISSUER=https://api-vexaaccount.onrender.com\nVEXA_ACCOUNT_FRONTEND=https://vexaaccount-management.onrender.com\nVEXA_SSO_CLIENT_ID=<register-in-VexaAccount-Owner-SSO>\nVEXA_SSO_CLIENT_SECRET=<store-only-in-server-secret-manager>\nVEXA_SSO_REDIRECT_URI=${redirect}\nJWT_SECRET=<your-${c.appKey}-own-jwt-secret>\nVEXA_BACKEND_URL=${c.backendUrl}\nVEXA_FRONTEND_USER_URL=${c.frontendUserUrl}\n${adminLine}`;
}

function backendSso() { return `const crypto = require('crypto');\nconst axios = require('axios');\nconst VEXA_ISSUER = String(process.env.VEXA_ACCOUNT_ISSUER || 'https://api-vexaaccount.onrender.com').replace(/\\/$/, '');\nconst CLIENT_ID = String(process.env.VEXA_SSO_CLIENT_ID || '').trim();\nconst CLIENT_SECRET = String(process.env.VEXA_SSO_CLIENT_SECRET || '').trim();\nconst REDIRECT_URI = String(process.env.VEXA_SSO_REDIRECT_URI || '').trim();\nconst APP_JWT_SECRET = String(process.env.JWT_SECRET || '').trim();\nif (!CLIENT_ID || !CLIENT_SECRET || !REDIRECT_URI || !APP_JWT_SECRET) throw new Error('VexaAccount SSO server configuration is incomplete');\nfunction challenge(v) { return crypto.createHash('sha256').update(v).digest('base64url'); }\nfunction authorizationUrl(state, verifier, loginHint = '', prompt = '') {\n  const q = new URLSearchParams({ client_id: CLIENT_ID, redirect_uri: REDIRECT_URI, response_type: 'code', scope: 'openid profile email account session applications notifications', state, code_challenge: challenge(verifier), code_challenge_method: 'S256' });\n  if (loginHint) q.set('login_hint', loginHint); if (prompt) q.set('prompt', prompt);\n  return VEXA_ISSUER + '/api/sso/authorize?' + q.toString();\n}\nasync function exchangeCode(code, verifier) { const r=await axios.post(VEXA_ISSUER+'/api/sso/token',new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:REDIRECT_URI,client_id:CLIENT_ID,client_secret:CLIENT_SECRET,code_verifier:verifier}),{headers:{'content-type':'application/x-www-form-urlencoded'},timeout:15000}); return r.data; }\nasync function userinfo(accessToken) { const r=await axios.get(VEXA_ISSUER+'/api/sso/userinfo',{headers:{Authorization:'Bearer '+accessToken},timeout:10000}); return r.data; }\nfunction b64(v) { return Buffer.from(v).toString('base64url'); }\nfunction signJwt(payload, expiresInSeconds = 3600) {\n  const now=Math.floor(Date.now()/1000); const header=b64(JSON.stringify({alg:'HS256',typ:'JWT'}));\n  const body=b64(JSON.stringify({...payload,iat:now,exp:now+expiresInSeconds}));\n  const input=header+'.'+body; const sig=crypto.createHmac('sha256',APP_JWT_SECRET).update(input).digest('base64url');\n  return input+'.'+sig;\n}\nfunction issueApplicationSession(identity) {\n  const sub=String(identity?.sub || identity?.id || '').trim(); if(!sub) throw new Error('VexaAccount userinfo did not contain a subject');\n  return signJwt({sub,iss:'vexaaccount',aud:'application',email:identity.email || null,name:identity.name || identity.username || null},3600);\n}\nmodule.exports = { authorizationUrl, exchangeCode, userinfo, issueApplicationSession };\n`; }

function backendRoute() { return `// Mount this router under /api/auth/vexaaccount. Keep both secrets server-side.\nconst express = require('express');\nconst crypto = require('crypto');\nconst { authorizationUrl, exchangeCode, userinfo, issueApplicationSession } = require('./vexaaccount-sso');\nconst router = express.Router();\nconst STATE_COOKIE='vexa_sso_state';\nconst SESSION_COOKIE='app_session';\nconst COOKIE_TTL=10*60;\nconst FRONTEND_URL=String(process.env.VEXA_FRONTEND_USER_URL || '').replace(/\\/$/,'');\nconst STATE_KEY=crypto.createHash('sha256').update(String(process.env.JWT_SECRET||''),'utf8').digest();\nfunction seal(value) {\n  const iv=crypto.randomBytes(12); const cipher=crypto.createCipheriv('aes-256-gcm',STATE_KEY,iv);\n  const data=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);\n  return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),data.toString('base64url')].join('.');\n}\nfunction open(value) {\n  const [ivB64,tagB64,dataB64]=String(value||'').split('.'); if(!ivB64||!tagB64||!dataB64) return null;\n  try { const decipher=crypto.createDecipheriv('aes-256-gcm',STATE_KEY,Buffer.from(ivB64,'base64url')); decipher.setAuthTag(Buffer.from(tagB64,'base64url')); const raw=Buffer.concat([decipher.update(Buffer.from(dataB64,'base64url')),decipher.final()]).toString('utf8'); return JSON.parse(raw); } catch { return null; }\n}\nfunction cookieOptions(maxAge) { return {httpOnly:true,secure:true,sameSite:'lax',path:'/api/auth/vexaaccount',maxAge}; }\nrouter.get('/login',(req,res)=>{ const state=crypto.randomBytes(32).toString('base64url'), verifier=crypto.randomBytes(32).toString('base64url'); res.cookie(STATE_COOKIE,seal({state,verifier,exp:Date.now()+COOKIE_TTL*1000}),cookieOptions(COOKIE_TTL*1000)); res.redirect(302,authorizationUrl(state,verifier,String(req.query.login_hint||''),'login')); });\nrouter.get('/callback',async(req,res,next)=>{ try { const tx=open(req.cookies?.[STATE_COOKIE]); const state=String(req.query.state||''),code=String(req.query.code||''); res.clearCookie(STATE_COOKIE,{...cookieOptions(0),maxAge:undefined}); if(!tx||tx.exp<Date.now()||tx.state!==state||!code) return res.status(400).json({error:'INVALID_SSO_TRANSACTION'}); const tokens=await exchangeCode(code,tx.verifier); const identity=await userinfo(tokens.access_token); const session=issueApplicationSession(identity); res.cookie(SESSION_COOKIE,session,{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:60*60*1000}); return res.redirect(302,FRONTEND_URL || '/'); } catch(e){next(e);} });\nmodule.exports = router;\n`; }

function frontendUser() { return `// VexaAccount user-side adapter. Do not put secrets in browser code.\nexport function startVexaAccountLogin({ backendUrl, loginHint = '', prompt = 'login' } = {}) { const base=String(backendUrl||'').replace(/\\/$/,''); const q=new URLSearchParams(); if(loginHint) q.set('login_hint',loginHint); if(prompt) q.set('prompt',prompt); window.location.assign(base+'/api/auth/vexaaccount/login?'+q.toString()); }\nexport function manageVexaAccount(url='https://vexaaccount-management.onrender.com') { window.location.assign(url); }\n`; }
function frontendAdmin() { return `// VexaAccount admin-side integration metadata. Never expose VEXA_SSO_CLIENT_SECRET or JWT_SECRET here.\nexport const vexaAccountIntegration = { issuer: 'https://api-vexaaccount.onrender.com', scopes: ['openid','profile','email','account','session','applications','notifications'] };\nexport function openVexaAccountAdmin(url='https://vexaaccount-management.onrender.com') { window.open(url,'_blank','noopener,noreferrer'); }\n`; }
function readme(c) {
  const redirect=`${c.backendUrl}/api/auth/vexaaccount/callback`;
  const adminEndpoint = c.hasAdminFrontend ? `- Admin frontend: ${c.frontendAdminUrl}` : '- Admin frontend: none (backend + user frontend topology)';
  const adminFile = c.hasAdminFrontend ? '- frontend-admin/src/integrations/vexaaccount.js\n' : '';
  return `# ${c.displayName} — VexaAccount SSO Kit\n\nGenerated by VexaAccount Owner SSO Application Kit.\n\n## Detected stack\n- Backend: ${c.framework}\n- Language: ${c.language}\n- Generator mode: complete Node.js/Express additive integration\n- Admin frontend: ${c.hasAdminFrontend ? 'enabled' : 'not configured'}\n\n## Integration contract\n- Register exact redirect URI: ${redirect}\n- Use Authorization Code + S256 PKCE.\n- Passwords stay on the VexaAccount origin.\n- The VexaAccount client secret stays in the application backend secret manager.\n- JWT_SECRET is the application's own session-signing secret; it is not sent to VexaAccount.\n- The generated state transaction is encrypted in a Secure/HttpOnly browser cookie, so it does not depend on an in-memory process and works across backend instances.\n- The callback creates a short-lived application-owned JWT session cookie; adapt the session claim handling to the application's existing authorization middleware.\n- Never copy Telegram/third-party browser cookies or raw tokens.\n\n## Application endpoints\n- Backend: ${c.backendUrl}\n- User frontend: ${c.frontendUserUrl}\n${adminEndpoint}\n\n## Generated files\n- backend/.env.vexaaccount.example\n- backend/src/integrations/vexaaccount-sso.js\n- backend/src/routes/vexaaccount-auth.js\n- frontend-user/src/integrations/vexaaccount.js\n${adminFile}- VEXAACCOUNT_SSO_INTEGRATION.md\n\nAfter installation, mount the generated router, set the environment variables, and register the exact callback URI in VexaAccount Owner SSO Control. Do not commit real secrets.\n`;
}

function fileManifest(files) {
  return files.map(f => ({ path: String(f.path), sha256: crypto.createHash('sha256').update(String(f.code ?? f.content ?? ''), 'utf8').digest('hex'), size: Buffer.byteLength(String(f.code ?? f.content ?? ''), 'utf8') }));
}

function generate(body) {
  const c=validateInput(body);
  const redirect=`${c.backendUrl}/api/auth/vexaaccount/callback`;
  const files=[
    {path:'backend/.env.vexaaccount.example',code:envExample(c)},
    {path:'backend/src/integrations/vexaaccount-sso.js',code:backendSso()},
    {path:'backend/src/routes/vexaaccount-auth.js',code:backendRoute()},
    {path:'frontend-user/src/integrations/vexaaccount.js',code:frontendUser()},
    ...(c.hasAdminFrontend ? [{path:'frontend-admin/src/integrations/vexaaccount.js',code:frontendAdmin()}] : []),
    {path:'VEXAACCOUNT_SSO_INTEGRATION.md',code:readme(c)}
  ];
  const manifest={generatorVersion:'1.4.0',application:c,topology:{backend:true,frontendUser:true,frontendAdmin:c.hasAdminFrontend},framework:c.framework,language:c.language,redirectUri:redirect,security:['authorization_code_pkce_s256','server_side_client_secret','encrypted_stateless_pkce_transaction','application_owned_jwt_session','no_third_party_cookie_copy'],generatedFiles:fileManifest(files),generatedAt:new Date().toISOString()};
  return { manifest, files };
}
module.exports = { generate, validateInput, fileManifest };