const API_BASE='https://api-vexaaccount.onrender.com';
const api=(path,options={})=>fetch(API_BASE+path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(path,options){const r=await api(path,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'Request failed: '+r.status);return d;}
let state={apps:[],audit:[],session:null,view:'overview',lastCreated:null};
function appKey(name){return String(name||'').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/-+/g,'-').replace(/^[-_]+|[-_]+$/g,'').slice(0,128);}
function nav(){return [['overview','Overview'],['applications','Applications'],['activity','SSO Activity'],['security','Security'],['settings','Platform Settings']].map(([id,label])=>'<button class="nav '+(state.view===id?'active':'')+'" data-view="'+id+'">'+label+'</button>').join('');}
function shell(content){const root=document.getElementById('app');root.innerHTML='<div class="console"><aside class="sidebar"><div class="brand"><span class="brand-mark">V</span><div><b>VexaAccount</b><small>ECOSYSTEM CONTROL</small></div></div><nav>'+nav()+'</nav><div class="side-footer"><span class="owner-dot"></span><div><b>'+esc(state.session.user.name||'Owner')+'</b><small>Super Owner</small></div></div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">VEXA ECOSYSTEM CONTROL</p><h1>Super Owner Console</h1></div><div class="top-actions"><span class="live"><i></i> System online</span><button id="createTop" class="primary">＋ Create application</button><button id="logout" class="secondary">Sign out</button></div></header><main class="content">'+content+'</main><nav class="bottom-nav">'+nav()+'</nav></section></div>';root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();});root.querySelector('#logout').onclick=logout;root.querySelector('#createTop').onclick=createApp;}
function overview(){const apps=state.apps;const active=apps.filter(a=>a.status==='active').length;const pending=apps.filter(a=>a.status==='pending').length;return '<section class="hero glass"><div><p class="eyebrow">CENTRAL IDENTITY PLATFORM</p><h2>Everything connected to VexaAccount, in one control plane.</h2><p>Manage approved applications, SSO lifecycle, credentials, scopes and security activity from one Owner console.</p></div><button id="heroCreate" class="primary">Create new integration</button></section><section class="metrics"><article class="metric glass"><small>Connected applications</small><strong>'+apps.length+'</strong><span>Registered ecosystem clients</span></article><article class="metric glass"><small>Active applications</small><strong>'+active+'</strong><span>Currently enabled for SSO</span></article><article class="metric glass"><small>Awaiting approval</small><strong>'+pending+'</strong><span>Pending Owner decision</span></article><article class="metric glass"><small>Recent security events</small><strong>'+state.audit.length+'</strong><span>Latest audit records</span></article></section><section class="grid"><article class="panel glass"><div class="section-head"><div><h2>Application health</h2><p class="muted">Latest registered integrations</p></div><button class="link" data-go="applications">View all</button></div>'+apps.slice(0,5).map(a=>'<div class="row"><div><b>'+esc(a.display_name||a.name||a.client_id)+'</b><small>'+esc(a.client_id)+'</small></div><span class="badge '+esc(a.status)+'">'+esc(a.status)+'</span></div>').join('')+'</article><article class="panel glass"><div class="section-head"><div><h2>Recent activity</h2><p class="muted">Owner and registry audit trail</p></div><button class="link" data-go="activity">View all</button></div>'+state.audit.slice(0,5).map(e=>'<div class="row"><div><b>'+esc(e.action||'Event')+'</b><small>'+esc(e.created_at||'')+'</small></div></div>').join('')+'</article></section>';}
function applications(){return '<section class="page-head"><div><h2>Application Registry</h2><p>Register, approve, configure, disable, rotate credentials, or revoke ecosystem applications.</p></div><button id="newApp" class="primary">＋ Create application</button></section><section class="panel glass"><div class="toolbar"><input id="search" placeholder="Search applications"><span>'+state.apps.length+' applications</span></div><div id="appList">'+state.apps.map(card).join('')+'</div></section>';}
function card(a){const name=a.display_name||a.name||a.client_id;const scopes=Array.isArray(a.allowedScopes)?a.allowedScopes.join(', '):'';return '<article class="app-card" data-app="'+esc(a.client_id)+'"><div class="app-main"><div class="app-icon">'+esc(name).slice(0,1).toUpperCase()+'</div><div><h3>'+esc(name)+'</h3><p>'+esc(a.application_key||'')+' · '+esc(a.client_id)+'</p><small>Scopes: '+esc(scopes||'Not configured')+'</small></div></div><div class="app-controls"><span class="badge '+esc(a.status)+'">'+esc(a.status)+'</span><button data-status="'+esc(a.client_id)+'">'+(a.status==='active'?'Disable':'Enable')+'</button><button data-rotate="'+esc(a.client_id)+'">Rotate secret</button><button data-revoke="'+esc(a.client_id)+'" class="danger">Revoke</button></div></article>';}
function activity(){return '<section class="page-head"><div><h2>SSO Activity & Audit</h2><p>Review control-plane activity and application lifecycle events.</p></div><button id="refreshAudit" class="secondary">Refresh</button></section><section class="panel glass">'+(state.audit.map(e=>'<article class="audit-row"><div class="event-dot"></div><div><h3>'+esc(e.action||'Event')+'</h3><p>'+esc(e.resource_type||'')+' '+esc(e.resource_id||'')+'</p><small>'+esc(e.created_at||'')+'</small></div></article>').join('')||'<p class="muted">No activity available.</p>')+'</section>';}
function security(){return '<section class="page-head"><div><h2>Security Control</h2><p>Use application lifecycle controls to contain access and rotate credentials.</p></div></section><section class="grid"><article class="panel glass"><h2>Credential lifecycle</h2><p class="muted">Client secrets are generated only at creation or rotation. Rotate any application secret from Application Registry.</p><button class="primary" data-go="applications">Open applications</button></article><article class="panel glass"><h2>Emergency access containment</h2><p class="muted">Disable or revoke an application to stop its SSO client access. Revocation is permanent.</p><button class="danger big" data-go="applications">Manage applications</button></article></section>';}
function settings(){return '<section class="page-head"><div><h2>Platform Settings</h2><p>VexaAccount is the central identity authority. Application-specific configuration is managed through the registry.</p></div></section><section class="panel glass"><h2>Available ecosystem scopes</h2><div class="scope-list">'+['openid','profile','email','account','session','applications','notifications'].map(s=>'<span>'+s+'</span>').join('')+'</div><p class="muted">Assign scopes during application creation. Backend environment secrets and infrastructure-level deployment settings remain protected from browser-based administration.</p></section>';}
function render(){let c=state.view==='overview'?overview():state.view==='applications'?applications():state.view==='activity'?activity():state.view==='security'?security():settings();shell(c);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.view=b.dataset.go;render();});document.querySelector('#heroCreate')?.addEventListener('click',createApp);document.querySelector('#newApp')?.addEventListener('click',createApp);document.querySelector('#refreshAudit')?.addEventListener('click',load);document.querySelector('#search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#appList').innerHTML=state.apps.filter(a=>JSON.stringify(a).toLowerCase().includes(q)).map(card).join('');bindAppControls();});bindAppControls();}
function bindAppControls(){document.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{await json('/api/sso-registry/applications/'+encodeURIComponent(b.dataset.status)+'/status',{method:'PATCH',body:JSON.stringify({status:b.textContent==='Disable'?'disabled':'active'})});await load();});document.querySelectorAll('[data-rotate]').forEach(b=>b.onclick=async()=>{const d=await json('/api/sso-registry/applications/'+encodeURIComponent(b.dataset.rotate)+'/rotate-secret',{method:'POST'});alert('New Client Secret:\n\n'+(d.clientSecret||'Secret returned. Store it securely.'));await load();});document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{if(confirm('Revoke this application permanently?')){await json('/api/sso-registry/applications/'+encodeURIComponent(b.dataset.revoke),{method:'DELETE'});await load();}});}
function closeReceipt(){document.querySelector('.receipt-overlay')?.remove();}
function showReceipt(data){
 const a=data.application||data.app||data; const clientId=a.clientId||a.client_id||data.clientId||'';
 const secret=data.clientSecret||data.clientJWT||data.clientJwt||data.clientSecretValue||'';
 const name=a.displayName||a.display_name||a.name||data.displayName||'VexaApp';
 const key=a.applicationKey||a.application_key||data.applicationKey||'';
 const redirects=(a.redirectUris||a.redirect_uris||data.redirectUris||[]).join(', ');
 const scopes=(a.allowedScopes||a.allowed_scopes||data.allowedScopes||[]).join(' ');
 state.lastCreated={name,key,redirects,scopes,clientId,secret,createdAt:new Date().toISOString()};
 const root=document.getElementById('app');
 root.insertAdjacentHTML('beforeend','<div class="receipt-overlay"><section class="receipt glass"><button class="receipt-close" id="closeReceipt" aria-label="Close">×</button><div class="receipt-hero"><span class="brand-mark">V</span><div><p class="eyebrow">VEXAACCOUNT • INTEGRATION RECEIPT</p><h2>Application created successfully</h2><p>Your VexaApp is ready for the next approval and integration steps.</p></div></div><div class="receipt-grid"><div><small>APPLICATION NAME</small><b>'+esc(name)+'</b></div><div><small>APPLICATION KEY</small><b>'+esc(key)+'</b></div><div class="wide"><small>REDIRECT URL</small><code>'+esc(redirects)+'</code></div><div class="wide"><small>CLIENT ID</small><div class="copy-row"><code id="receiptClientId">'+esc(clientId)+'</code><button data-copy="receiptClientId">Copy</button></div></div><div class="wide secret"><small>CLIENT JWT / SECRET</small><div class="copy-row"><code id="receiptSecret">'+esc(secret)+'</code><button data-copy="receiptSecret">Copy</button></div><p>This secret is shown only at creation time. Store it securely and rotate it if exposed.</p></div><div class="wide"><small>GRANTED ECOSYSTEM SCOPES</small><code>'+esc(scopes)+'</code></div></div><div class="env-card"><p class="eyebrow">READY TO COPY INTO YOUR APPLICATION</p><code id="envConfig">VEXA_ACCOUNT_SSO_CONFIG='+esc(JSON.stringify({url:'https://api-vexaaccount.onrender.com',clientId:clientId,clientSecret:secret,redirectUri:redirects.split(', ')[0]||'',timeoutMs:10000}))+'</code><button data-copy="envConfig">Copy configuration</button></div><div class="receipt-actions"><button id="downloadReceipt" class="primary">↓ Save integration receipt as PDF</button><button id="closeReceiptSecondary" class="secondary">Done</button></div></section></div>');
 document.querySelector('#closeReceipt').onclick=closeReceipt;document.querySelector('#closeReceiptSecondary').onclick=closeReceipt;
 document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const el=document.getElementById(b.dataset.copy);try{await navigator.clipboard.writeText(el.textContent);b.textContent='Copied ✓';setTimeout(()=>b.textContent=b.dataset.copy==='envConfig'?'Copy configuration':'Copy',1500);}catch{alert('Copy failed. Please copy the value manually.');}});
 document.querySelector('#downloadReceipt').onclick=downloadReceiptPdf;
}
function pdfEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function downloadReceiptPdf(){
 const d=state.lastCreated;if(!d)return;
 if(!window.jspdf?.jsPDF){alert('PDF generator is still loading. Please wait a moment and try again.');return;}
 const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});
 doc.setFillColor(7,10,18);doc.rect(0,0,210,297,'F');
 doc.setFillColor(124,58,237);doc.roundedRect(15,15,180,30,5,5,'F');
 doc.setTextColor(255,255,255);doc.setFontSize(24);doc.text('VexaAccount',24,31);doc.setFontSize(9);doc.text('CENTRAL IDENTITY PLATFORM • APPLICATION INTEGRATION RECEIPT',24,38);
 let y=58;doc.setTextColor(220,230,255);doc.setFontSize(18);doc.text('Application created successfully',15,y);y+=12;
 doc.setFontSize(9);doc.setTextColor(150,165,195);doc.text('Secure integration details generated by the VexaAccount Super Owner Console',15,y);y+=12;
 const rows=[['APPLICATION NAME',d.name],['APPLICATION KEY',d.key],['REDIRECT URL',d.redirects],['CLIENT ID',d.clientId],['CLIENT JWT / SECRET',d.secret],['ECOSYSTEM SCOPES',d.scopes],['CREATED AT',d.createdAt],['VEXAACCOUNT SSO URL','https://api-vexaaccount.onrender.com']];
 rows.forEach(([label,value])=>{doc.setFillColor(18,25,42);doc.roundedRect(15,y,180,22,3,3,'F');doc.setTextColor(125,211,252);doc.setFontSize(7);doc.text(label,20,y+7);doc.setTextColor(245,248,255);doc.setFontSize(8);const lines=doc.splitTextToSize(String(value||''),165);doc.text(lines,20,y+13);y+=Math.max(26,13+lines.length*4);if(y>245){doc.addPage();doc.setFillColor(7,10,18);doc.rect(0,0,210,297,'F');y=20;}});
 doc.setFillColor(17,24,39);doc.roundedRect(15,y,180,32,4,4,'F');doc.setTextColor(125,211,252);doc.setFontSize(8);doc.text('READY-TO-COPY ENVIRONMENT VARIABLE',20,y+7);doc.setTextColor(245,248,255);doc.setFontSize(7);const env='VEXA_ACCOUNT_SSO_CONFIG='+JSON.stringify({url:'https://api-vexaaccount.onrender.com',clientId:d.clientId,clientSecret:d.secret,redirectUri:(d.redirects||'').split(', ')[0],timeoutMs:10000});doc.text(doc.splitTextToSize(env,165),20,y+14);
 y+=42;doc.setTextColor(150,165,195);doc.setFontSize(8);doc.text('Security notice: This PDF contains a client secret. Store it securely and do not share it publicly.',15,Math.min(y,285));
 doc.save((d.key||'vexaaccount-application')+'-integration-receipt.pdf');
}
async function createApp(){const name=prompt('Application name');if(!name)return;const key=appKey(name);if(!/^[a-z0-9][a-z0-9_-]{1,127}$/.test(key))return alert('Enter a valid application name.');const redirectUri=prompt('Redirect URI');if(!redirectUri)return;try{const d=await json('/api/sso-registry/applications',{method:'POST',body:JSON.stringify({displayName:name,applicationKey:key,redirectUris:[redirectUri],allowedScopes:['openid','profile','email','account','session','applications','notifications'],environment:'production'})});showReceipt(d);await load();}catch(e){alert(e.message);}}
async function logout(){await api('/api/auth/super-admin/logout',{method:'POST'});renderLogin();}
function renderLogin(msg=''){document.getElementById('app').innerHTML='<main class="login"><section class="login-card glass"><span class="brand-mark">V</span><p class="eyebrow">VEXA ECOSYSTEM CONTROL</p><h1>Owner Sign in</h1><p class="muted">Secure access to the VexaAccount control plane.</p><form id="login"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="primary" type="submit">Unlock control plane</button><p class="error">'+esc(msg)+'</p></form></section></main>';document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);const d=await json('/api/auth/super-admin/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});if(!d.success)throw new Error(d.message||'Login failed');await load();}catch(x){renderLogin(x.message);}};}
async function load(){try{const session=await json('/api/auth/super-admin/session');if(!session.success)return renderLogin();state.session=session;const [apps,audit]=await Promise.all([json('/api/sso-registry/applications'),json('/api/sso-registry/audit')]);state.apps=apps.applications||[];state.audit=audit.events||[];render();}catch(e){renderLogin(e.message);}}
load();