const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { authenticator } = require('otplib');
const { pool } = require('../config/database');

const router = express.Router();
const JWT_SECRET = process.env.JWT_SECRET;
function token(req){const h=req.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7).trim():req.cookies?.vexaccount_session||null;}
function requireUser(req,res,next){try{const t=token(req);if(!t)return res.status(401).json({success:false,message:'Authentication required'});const c=jwt.verify(t,JWT_SECRET),id=c.sub||c.id;if(!id||c.role!=='user')return res.status(401).json({success:false,message:'Invalid identity'});req.accountUserId=id;next();}catch{return res.status(401).json({success:false,message:'Invalid or expired session'});}}
router.use(requireUser);
router.get('/profile',async(req,res,next)=>{try{const [rows]=await pool.query('SELECT id,email,name,avatar_url,first_name,last_name,gender,dob,country,is_verified,is_active,created_at FROM store_users WHERE id=? LIMIT 1',[req.accountUserId]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});res.json({success:true,user:rows[0]});}catch(e){next(e);}});
router.patch('/profile',async(req,res,next)=>{try{const allowed=['name','first_name','last_name','gender','dob','country','avatar_url'],fields=[],values=[];for(const key of allowed)if(Object.prototype.hasOwnProperty.call(req.body,key)){fields.push(`${key}=?`);values.push(req.body[key]||null);}if(!fields.length)return res.status(400).json({success:false,message:'No profile changes supplied'});values.push(req.accountUserId);await pool.query(`UPDATE store_users SET ${fields.join(', ')} WHERE id=?`,values);res.json({success:true,message:'Profile updated'});}catch(e){next(e);}});
router.patch('/email',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email||!password)return res.status(400).json({success:false,message:'Email and current password are required'});const [rows]=await pool.query('SELECT password FROM store_users WHERE id=? LIMIT 1',[req.accountUserId]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(password,rows[0].password))return res.status(401).json({success:false,message:'Current password is incorrect'});const [taken]=await pool.query('SELECT id FROM store_users WHERE email=? AND id<>? LIMIT 1',[email,req.accountUserId]);if(taken.length)return res.status(409).json({success:false,message:'Email is already in use'});await pool.query('UPDATE store_users SET email=?,is_verified=0 WHERE id=?',[email,req.accountUserId]);res.json({success:true,message:'Email changed. Verification is required before normal sign-in.',requiresVerification:true});}catch(e){next(e);}});
router.patch('/password',async(req,res,next)=>{try{const current=String(req.body.currentPassword||''),nextPassword=String(req.body.newPassword||'');if(!current)return res.status(400).json({success:false,message:'Current password is required'});if(nextPassword.length<8)return res.status(400).json({success:false,message:'New password must be at least 8 characters'});const [rows]=await pool.query('SELECT password FROM store_users WHERE id=? LIMIT 1',[req.accountUserId]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(current,rows[0].password))return res.status(401).json({success:false,message:'Current password is incorrect'});await pool.query('UPDATE store_users SET password=? WHERE id=?',[await bcrypt.hash(nextPassword,12),req.accountUserId]);await pool.query('UPDATE sso_sessions SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[req.accountUserId]);res.clearCookie('vexaccount_session',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.COOKIE_SAME_SITE||'lax',path:'/'});res.json({success:true,message:'Password changed. Please sign in again.'});}catch(e){next(e);}});
router.get('/preferences',async(req,res,next)=>{try{await pool.query('INSERT IGNORE INTO vexa_account_preferences (user_id) VALUES (?)',[req.accountUserId]);const [rows]=await pool.query('SELECT locale,timezone,marketing_email_enabled,security_email_enabled,updated_at FROM vexa_account_preferences WHERE user_id=?',[req.accountUserId]);res.json({success:true,preferences:rows[0]||{}});}catch(e){next(e);}});
router.patch('/preferences',async(req,res,next)=>{try{await pool.query('INSERT IGNORE INTO vexa_account_preferences (user_id) VALUES (?)',[req.accountUserId]);const p=req.body||{};await pool.query('UPDATE vexa_account_preferences SET locale=COALESCE(?,locale),timezone=COALESCE(?,timezone),marketing_email_enabled=COALESCE(?,marketing_email_enabled),security_email_enabled=COALESCE(?,security_email_enabled) WHERE user_id=?',[p.locale||null,p.timezone||null,p.marketing_email_enabled==null?null:(p.marketing_email_enabled?1:0),p.security_email_enabled==null?null:(p.security_email_enabled?1:0),req.accountUserId]);res.json({success:true,message:'Preferences updated'});}catch(e){next(e);}});
router.get('/security',async(req,res,next)=>{try{const [u]=await pool.query('SELECT twofa_enabled,email_2fa_enabled,passcode_enabled FROM store_users WHERE id=?',[req.accountUserId]);const [s]=await pool.query('SELECT two_factor_enabled,security_notifications_enabled FROM vexa_account_security_settings WHERE user_id=?',[req.accountUserId]);res.json({success:true,security:{...(u[0]||{}),...(s[0]||{})}});}catch(e){next(e);}});
router.post('/security/2fa/setup',async(req,res,next)=>{try{const password=String(req.body.password||'');const [u]=await pool.query('SELECT email,password,twofa_enabled FROM store_users WHERE id=? AND is_active=1',[req.accountUserId]);if(!u.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(password,u[0].password))return res.status(401).json({success:false,message:'Password is incorrect'});if(u[0].twofa_enabled)return res.status(409).json({success:false,message:'Authenticator 2FA is already enabled'});const secret=authenticator.generateSecret();const otpauth=authenticator.keyuri(u[0].email,'VexaAccount',secret);res.json({success:true,secret,otpauth});}catch(e){next(e);}});
router.post('/security/2fa/enable',async(req,res,next)=>{try{const secret=String(req.body.secret||''),otp=String(req.body.token||''),password=String(req.body.password||'');if(!secret||!otp||!password)return res.status(400).json({success:false,message:'Secret, code and password are required'});const [u]=await pool.query('SELECT email,password FROM store_users WHERE id=? AND is_active=1',[req.accountUserId]);if(!u.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(password,u[0].password))return res.status(401).json({success:false,message:'Password is incorrect'});if(!authenticator.check(otp,secret))return res.status(400).json({success:false,message:'Invalid authenticator code'});await pool.query('UPDATE store_users SET twofa_enabled=1,twofa_secret=?,email_2fa_enabled=0 WHERE id=?',[secret,req.accountUserId]);await pool.query('INSERT INTO vexa_account_security_settings (user_id,two_factor_enabled) VALUES (?,1) ON DUPLICATE KEY UPDATE two_factor_enabled=1',[req.accountUserId]);res.json({success:true,message:'Authenticator 2FA enabled successfully'});}catch(e){next(e);}});
router.post('/security/disable-2fa',async(req,res,next)=>{try{const password=String(req.body.password||'');const [rows]=await pool.query('SELECT password FROM store_users WHERE id=?',[req.accountUserId]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(password,rows[0].password))return res.status(401).json({success:false,message:'Password is incorrect'});await pool.query('UPDATE store_users SET twofa_enabled=0,twofa_secret=NULL,email_2fa_enabled=0 WHERE id=?',[req.accountUserId]);await pool.query('INSERT INTO vexa_account_security_settings (user_id,two_factor_enabled) VALUES (?,0) ON DUPLICATE KEY UPDATE two_factor_enabled=0',[req.accountUserId]);res.json({success:true,message:'Two-factor authentication disabled'});}catch(e){next(e);}});
router.post('/security/disable-passcode',async(req,res,next)=>{try{const password=String(req.body.password||'');if(!password)return res.status(400).json({success:false,message:'Password is required'});const [rows]=await pool.query('SELECT password FROM store_users WHERE id=?',[req.accountUserId]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(password,rows[0].password))return res.status(401).json({success:false,message:'Password is incorrect'});await pool.query('UPDATE store_users SET passcode_enabled=0,passcode_hash=NULL WHERE id=?',[req.accountUserId]);res.json({success:true,message:'Passcode disabled'});}catch(e){next(e);}});
router.get('/credits',async(req,res,next)=>{try{await pool.query('INSERT IGNORE INTO vexa_user_credit_balances(user_id) VALUES(?)',[req.accountUserId]);const [b]=await pool.query('SELECT credit_score,coins,updated_at FROM vexa_user_credit_balances WHERE user_id=?',[req.accountUserId]);const [l]=await pool.query('SELECT credit_score_delta,coins_delta,reason,created_at FROM vexa_user_credit_ledger WHERE user_id=? ORDER BY id DESC LIMIT 50',[req.accountUserId]);res.json({success:true,balance:b[0]||{},ledger:l});}catch(e){next(e);}});
router.get('/storage',async(req,res,next)=>{try{const [rows]=await pool.query('SELECT id,provider,storage_key,display_name,content_type,size_bytes,status,metadata,created_at,updated_at FROM vexa_user_storage_records WHERE user_id=? ORDER BY updated_at DESC',[req.accountUserId]);res.json({success:true,records:rows});}catch(e){next(e);}});
router.delete('/storage/:id',async(req,res,next)=>{try{const [r]=await pool.query('DELETE FROM vexa_user_storage_records WHERE id=? AND user_id=?',[req.params.id,req.accountUserId]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Storage record not found'});res.json({success:true,message:'Storage record removed'});}catch(e){next(e);}});
router.delete('/account',async(req,res,next)=>{const conn=await pool.getConnection();try{const password=String(req.body.password||'');const [rows]=await conn.query('SELECT password FROM store_users WHERE id=?',[req.accountUserId]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});if(!await bcrypt.compare(password,rows[0].password))return res.status(401).json({success:false,message:'Password is incorrect'});await conn.beginTransaction();await conn.query('UPDATE sso_sessions SET revoked_at=NOW() WHERE user_id=?',[req.accountUserId]);await conn.query('UPDATE sso_consents SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[req.accountUserId]);await conn.query('DELETE FROM vexa_account_preferences WHERE user_id=?',[req.accountUserId]);await conn.query('DELETE FROM vexa_account_security_settings WHERE user_id=?',[req.accountUserId]);await conn.query('DELETE FROM vexa_user_storage_records WHERE user_id=?',[req.accountUserId]);await conn.query('DELETE FROM vexa_user_credit_ledger WHERE user_id=?',[req.accountUserId]);await conn.query('DELETE FROM vexa_user_credit_balances WHERE user_id=?',[req.accountUserId]);await conn.query('DELETE FROM store_users WHERE id=?',[req.accountUserId]);await conn.commit();res.clearCookie('vexaccount_session',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.COOKIE_SAME_SITE||'lax',path:'/'});res.json({success:true,message:'Account deleted'});}catch(e){await conn.rollback().catch(()=>{});next(e);}finally{conn.release();}});
module.exports=router;
