const express=require('express');const jwt=require('jsonwebtoken');const {pool}=require('../config/database');const router=express.Router();const JWT_SECRET=process.env.JWT_SECRET;
function getToken(req){const h=req.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7).trim():req.cookies?.vexaccount_session||null}
function requireUser(req,res,next){try{const t=getToken(req);if(!t)return res.status(401).json({success:false,message:'Authentication required'});const c=jwt.verify(t,JWT_SECRET),userId=c.sub||c.id;if(!userId||c.role!=='user')return res.status(401).json({success:false,message:'User authentication required'});req.accountUser={...c,userId,sessionToken:t};next()}catch{return res.status(401).json({success:false,message:'Invalid or expired session'})}}
router.use(requireUser);
router.get('/apps',async(req,res,next)=>{try{const [rows]=await pool.query(`SELECT r.client_id,r.display_name,r.application_key,r.environment,r.status,r.description,c.is_active,c.last_used_at,co.scopes,co.granted_at FROM sso_client_registry r LEFT JOIN sso_clients c ON c.client_id=r.client_id LEFT JOIN sso_consents co ON co.client_id=r.client_id AND co.user_id=? AND co.revoked_at IS NULL ORDER BY r.display_name ASC`,[req.accountUser.userId]);res.json({success:true,applications:rows})}catch(e){next(e)}});
router.get('/sessions',async(req,res,next)=>{try{const [rows]=await pool.query(`SELECT s.id,s.client_id,r.display_name,s.scope,s.created_at,s.last_seen_at,s.expires_at FROM sso_sessions s LEFT JOIN sso_client_registry r ON r.client_id=s.client_id WHERE s.user_id=? AND s.revoked_at IS NULL AND s.expires_at>NOW() ORDER BY s.last_seen_at DESC`,[req.accountUser.userId]);const now=new Date();const exp=Number(req.accountUser.exp||0)*1000;const current={id:'current',client_id:'vexaaccount',display_name:'VexaAccount Account Center',scope:'account session',created_at:new Date(Number(req.accountUser.iat||0)*1000||now).toISOString(),last_seen_at:now.toISOString(),expires_at:new Date(exp||Date.now()+3600000).toISOString(),current:true};res.json({success:true,sessions:[current,...rows]})}catch(e){next(e)}});
router.delete('/sessions/:id',async(req,res,next)=>{try{if(String(req.params.id)==='current'){res.clearCookie('vexaccount_session',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.COOKIE_SAME_SITE||'lax',path:'/'});await pool.query('INSERT INTO sso_security_events (user_id,event_type,metadata) VALUES (?,?,?)',[req.accountUser.userId,'account.session_revoked',JSON.stringify({session_id:'current'})]);return res.json({success:true,message:'Current session revoked',logout:true})}const [r]=await pool.query('UPDATE sso_sessions SET revoked_at=NOW() WHERE id=? AND user_id=? AND revoked_at IS NULL',[req.params.id,req.accountUser.userId]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Session not found'});await pool.query('INSERT INTO sso_security_events (user_id,event_type,metadata) VALUES (?,?,?)',[req.accountUser.userId,'sso.session_revoked',JSON.stringify({session_id:req.params.id})]);res.json({success:true,message:'Session revoked'})}catch(e){next(e)}});
router.delete('/apps/:clientId/consent',async(req,res,next)=>{try{const [r]=await pool.query('UPDATE sso_consents SET revoked_at=NOW() WHERE client_id=? AND user_id=? AND revoked_at IS NULL',[req.params.clientId,req.accountUser.userId]);await pool.query('UPDATE sso_sessions SET revoked_at=NOW() WHERE client_id=? AND user_id=? AND revoked_at IS NULL',[req.params.clientId,req.accountUser.userId]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Application consent not found'});await pool.query('INSERT INTO sso_security_events (user_id,client_id,event_type,metadata) VALUES (?,?,?,?)',[req.accountUser.userId,req.params.clientId,'sso.application_access_revoked',JSON.stringify({source:'account_center'})]);res.json({success:true,message:'Application access revoked'})}catch(e){next(e)}});
router.get('/security/events',async(req,res,next)=>{try{const limit=Math.min(Math.max(Number(req.query.limit)||50,1),100);const [rows]=await pool.query('SELECT id,client_id,event_type,ip_address,user_agent,metadata,created_at FROM sso_security_events WHERE user_id=? ORDER BY created_at DESC LIMIT ?',[req.accountUser.userId,limit]);res.json({success:true,events:rows})}catch(e){next(e)}});module.exports=router;
