const crypto=require('crypto');
const axios=require('axios');
const {pool}=require('../config/database');
const jwt=require('jsonwebtoken');
const router=require('express').Router();
const JWT_SECRET=process.env.JWT_SECRET;
function auth(req,res,next){try{const h=req.get('authorization')||'';const t=h.startsWith('Bearer ')?h.slice(7).trim():req.cookies?.vexaccount_session;if(!t)throw Error();const c=jwt.verify(t,JWT_SECRET);if(c.role!=='user')throw Error();req.accountUserId=c.sub||c.id;if(!req.accountUserId)throw Error();next()}catch{return res.status(401).json({success:false,message:'Authentication required'})}}
function config(){const cloud=String(process.env.CLOUDINARY_CLOUD_NAME||'').trim(),key=String(process.env.CLOUDINARY_API_KEY||'').trim(),secret=String(process.env.CLOUDINARY_API_SECRET||'').trim();if(!cloud||!key||!secret)throw Error('Cloudinary is not configured');return {cloud,key,secret}}
function sign(params,secret){return crypto.createHash('sha1').update(Object.keys(params).filter(k=>params[k]!==undefined&&params[k]!==null&&params[k]!==''&&k!=='file'&&k!=='api_key').sort().map(k=>`${k}=${params[k]}`).join('&')+secret).digest('hex')}
router.use(auth);
router.post('/cloudinary-upload',async(req,res,next)=>{try{const {cloud,key,secret}=config();const dataUrl=String(req.body?.dataUrl||'');const displayName=String(req.body?.displayName||'VexaAccount file').trim().slice(0,180);if(!/^data:(image|video|application\/pdf|text)\/[\w.+-]+;base64,/i.test(dataUrl))return res.status(400).json({success:false,message:'Only supported image, video, PDF or text data URLs are accepted'});if(dataUrl.length>12*1024*1024)return res.status(413).json({success:false,message:'File is too large'});const timestamp=Math.floor(Date.now()/1000),folder=`vexaaccount/users/${req.accountUserId}`,params={folder,timestamp},signature=sign(params,secret),endpoint=`https://api.cloudinary.com/v1_1/${encodeURIComponent(cloud)}/auto/upload`,body=new URLSearchParams({file:dataUrl,folder,timestamp:String(timestamp),api_key:key,signature});const {data}=await axios.post(endpoint,body.toString(),{headers:{'Content-Type':'application/x-www-form-urlencoded'},maxContentLength:15*1024*1024,maxBodyLength:15*1024*1024,timeout:30000});const metadata=JSON.stringify({public_id:data.public_id,resource_type:data.resource_type,format:data.format,width:data.width,height:data.height,bytes:data.bytes,secure_url:data.secure_url});await pool.query('INSERT INTO vexa_user_storage_records (user_id,provider,storage_key,display_name,content_type,size_bytes,status,metadata) VALUES (?,?,?,?,?,?,?,?)',[req.accountUserId,'cloudinary',data.public_id,displayName,data.resource_type||null,Number(data.bytes||0),'ready',metadata]);res.status(201).json({success:true,message:'File uploaded to Cloudinary',file:{publicId:data.public_id,url:data.secure_url,bytes:data.bytes,resourceType:data.resource_type,format:data.format}})}catch(e){next(e)}});
module.exports=router;
