const express=require('express');
const {pool}=require('../config/database');
const {requireSuperAdmin}=require('../middleware/superAdminAuth');
const {auditAdminAction}=require('../middleware/adminAudit');
const router=express.Router();router.use(requireSuperAdmin);
async function ensure(){await pool.query(`CREATE TABLE IF NOT EXISTS vexa_account_support_messages (id BIGINT AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT NOT NULL,user_id BIGINT NOT NULL,sender_type ENUM('user','support') NOT NULL,message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(ticket_id),INDEX(user_id))`);}
router.get('/tickets',auditAdminAction('owner.support.list','vexa_account_support_ticket'),async(req,res,next)=>{try{await ensure();const status=String(req.query.status||'').trim();const where=status?'WHERE t.status=?':'';const params=status?[status]:[];const [rows]=await pool.query(`SELECT t.id,t.user_id,t.subject,t.message,t.status,t.created_at,t.updated_at,u.email,u.name FROM vexa_account_support_tickets t JOIN store_users u ON u.id=t.user_id ${where} ORDER BY t.updated_at DESC LIMIT 200`,params);res.json({success:true,tickets:rows});}catch(e){next(e);}});
router.get('/tickets/:id',auditAdminAction('owner.support.view','vexa_account_support_ticket'),async(req,res,next)=>{try{await ensure();const [t]=await pool.query('SELECT t.id,t.user_id,t.subject,t.message,t.status,t.created_at,t.updated_at,u.email,u.name FROM vexa_account_support_tickets t JOIN store_users u ON u.id=t.user_id WHERE t.id=?',[req.params.id]);if(!t.length)return res.status(404).json({success:false,message:'Ticket not found'});const [m]=await pool.query('SELECT id,sender_type,message,created_at FROM vexa_account_support_messages WHERE ticket_id=? AND user_id=? ORDER BY created_at ASC',[req.params.id,t[0].user_id]);res.json({success:true,ticket:{...t[0],messages:m}});}catch(e){next(e);}});
router.post('/tickets/:id/replies',auditAdminAction('owner.support.reply','vexa_account_support_ticket'),async(req,res,next)=>{try{await ensure();const message=String(req.body?.message||'').trim();if(!message)return res.status(400).json({success:false,message:'Reply message is required'});const [t]=await pool.query('SELECT id,user_id,status FROM vexa_account_support_tickets WHERE id=?',[req.params.id]);if(!t.length)return res.status(404).json({success:false,message:'Ticket not found'});const c=await pool.getConnection();try{await c.beginTransaction();await c.query('INSERT INTO vexa_account_support_messages(ticket_id,user_id,sender_type,message) VALUES(?, ?, "support", ?)',[t[0].id,t[0].user_id,message]);await c.query('UPDATE vexa_account_support_tickets SET status="pending_user",updated_at=NOW() WHERE id=?',[t[0].id]);await c.query('INSERT INTO vexa_account_notifications(user_id,type,title,message) VALUES(?,"support","Support replied",?)',[t[0].user_id,`Support replied to ticket #${t[0].id}: ${message}`]);await c.commit();res.status(201).json({success:true,message:'Support reply sent'});}catch(e){await c.rollback();throw e}finally{c.release()}}catch(e){next(e);}});
router.patch('/tickets/:id/status',auditAdminAction('owner.support.status','vexa_account_support_ticket'),async(req,res,next)=>{try{const allowed=['open','pending_user','closed'];const status=String(req.body?.status||'');if(!allowed.includes(status))return res.status(400).json({success:false,message:'Invalid ticket status'});const [r]=await pool.query('UPDATE vexa_account_support_tickets SET status=?,updated_at=NOW() WHERE id=?',[status,req.params.id]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Ticket not found'});const [t]=await pool.query('SELECT user_id FROM vexa_account_support_tickets WHERE id=?',[req.params.id]);if(t.length)await pool.query('INSERT INTO vexa_account_notifications(user_id,type,title,message) VALUES(?,"support","Support ticket updated",?)',[t[0].user_id,`Your support ticket #${req.params.id} is now ${status}.`]);res.json({success:true,message:'Ticket status updated'});}catch(e){next(e);}});
module.exports=router;
