(()=>{'use strict';
const KEY='vexachat_preferences_v1',FOLDER_KEY='vexachat_custom_folders_v1',DRAFT_KEY='vexachat_drafts_v1';
const defaults={appearance:'system',density:'comfortable',enter_to_send:true,animations:true,link_previews:true,autoplay_media:false,read_receipts:true,last_seen:'everyone',profile_photo:'everyone',calls_from:'contacts',message_preview:true,desktop_notifications:true,calls_enabled:true,notification_sound:true,notification_vibrate:true,private_notifications:true,group_notifications:true,channel_notifications:true,in_chat_sounds:true,save_media:false,auto_download_mobile:true,auto_download_wifi:true,auto_download_roaming:false,autoplay_gifs:false,autoplay_videos:false,streaming:true,use_less_data_calls:false,language:'English',data_saver:false};
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}};
const save=p=>{try{localStorage.setItem(KEY,JSON.stringify(p))}catch{}};
const folders=()=>{try{const v=JSON.parse(localStorage.getItem(FOLDER_KEY)||'[]');return Array.isArray(v)?v.filter(x=>x&&x.id&&x.name):[]}catch{return[]}};
const saveFolders=v=>{try{localStorage.setItem(FOLDER_KEY,JSON.stringify(v))}catch{}};
const applyPreferences=p=>{document.documentElement.dataset.theme=p.appearance;document.documentElement.dataset.density=p.density;document.documentElement.dataset.motion=p.animations?'on':'off'};
const bytesOfStorage=()=>{let n=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';const v=localStorage.getItem(k)||'';n+=(k.length+v.length)*2}}catch{}return n};
const fmtBytes=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';
applyPreferences(load());
function open(ctx,initialSection){
 const p=load();const ns=ctx.state.settings||{};
 Object.assign(p,{desktop_notifications:ns.messages_enabled!==0,message_preview:ns.previews_enabled!==0,calls_enabled:ns.calls_enabled!==0});
 let section=['account','privacy','notifications','chats','appearance','folders','devices','data','language','premium','help'].includes(initialSection)?initialSection:'account';
 const sections=[['account','Account','Identity and profile'],['privacy','Privacy & Security','Visibility and calls'],['notifications','Notifications & Sounds','Alerts and previews'],['chats','Chat Settings','Composer and media'],['appearance','Appearance','Theme and density'],['folders','Chat Folders','Organize conversations'],['devices','Devices','Signed-in session'],['data','Data & Storage','Network and media'],['language','Language','Interface language'],['premium','VexaChat Premium','Premium features'],['help','Help & FAQ','Support and answers']];
 const esc=s=>ctx.esc(String(s??''));
 const row=(label,desc,control)=>'<div class="settings-row"><div><strong>'+esc(label)+'</strong><small>'+esc(desc)+'</small></div>'+control+'</div>';
 const toggle=(id,on)=>'<label class="switch"><input id="'+id+'" type="checkbox" '+(on?'checked':'')+'><span></span></label>';
 const select=(id,values,value)=>'<select class="settings-select" id="'+id+'">'+values.map(v=>'<option value="'+esc(v)+'" '+(v===value?'selected':'')+'>'+esc(v==='myanmar'?'မြန်မာ':v[0].toUpperCase()+v.slice(1))+'</option>').join('')+'</select>';
 const heading=(t,d)=>'<div class="settings-heading"><h3>'+esc(t)+'</h3><p>'+esc(d)+'</p></div>';
 const icon=x=>({account:'●',privacy:'⌁',notifications:'◉',chats:'▣',appearance:'◐',folders:'▤',devices:'▤',data:'⇅',language:'文',premium:'✦',help:'?'})[x]||'•';
 const notifySave=async()=>{try{ctx.state.settings=(await ctx.api('/api/chat/notifications/settings',{method:'PUT',body:JSON.stringify({messages_enabled:p.desktop_notifications,calls_enabled:p.calls_enabled,previews_enabled:p.message_preview})})).settings;ctx.notify('Notification settings saved')}catch(e){ctx.notify(e.message)}};
 const savePrivacy=async()=>{try{await ctx.api('/api/chat/privacy/settings',{method:'PATCH',body:JSON.stringify({read_receipts:p.read_receipts,last_seen:p.last_seen,profile_photo:p.profile_photo,calls_from:p.calls_from})});ctx.notify('Privacy settings saved')}catch(e){ctx.notify(e.message)}};
 function render(){const body={account,privacy,notifications,chats,appearance,foldersView,devices,data,language,premium,help}[section]();ctx.modal('VexaChat Settings','<div class="settings-layout"><nav class="settings-nav">'+sections.map(s=>'<button class="'+(s[0]===section?'active':'')+'" data-setting="'+s[0]+'"><span>'+icon(s[0])+'</span><b>'+esc(s[1])+'</b><small>'+esc(s[2])+'</small></button>').join('')+'</nav><section class="settings-content">'+body+'</section></div>');document.querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>{section=b.dataset.setting;render()});bind()}
 function account(){const m=ctx.state.me||{};const url=m.avatar_url||m.picture||m.avatar||'';const avatar=url?'<div class="avatar avatar-image"><img src="'+esc(url)+'" alt="" loading="lazy"><span>'+esc(ctx.initials(m.name||m.email))+'</span></div>':'<div class="avatar">'+esc(ctx.initials(m.name||m.email))+'</div>';return heading('Account','Manage the VexaAccount identity used by VexaChat')+'<div class="settings-profile">'+avatar+'<div><strong>'+esc(m.name||'VexaAccount user')+'</strong><small>'+esc(m.email||'')+'</small></div></div><div class="settings-card"><button class="settings-action" id="editProfile"><b>Edit profile</b><span>Display name, bio and profile photo</span></button><button class="settings-action" id="securitySettings"><b>Account security</b><span>Password and two-step verification</span></button><button class="settings-action" id="signOut"><b>Sign out</b><span>End this VexaChat session</span></button></div>'}
 function privacy(){return heading('Privacy & Security','Control visibility, read state and incoming calls')+'<div class="settings-card">'+row('Read receipts','Show when messages are read',toggle('read_receipts',p.read_receipts))+row('Last seen','Who can see your online activity',select('last_seen',['everyone','contacts','nobody'],p.last_seen))+row('Profile photo','Who can view your profile photo',select('profile_photo',['everyone','contacts','nobody'],p.profile_photo))+row('Calls','Who can start calls with you',select('calls_from',['everyone','contacts','nobody'],p.calls_from))+'</div>'}
 function notifications(){return heading('Notifications & Sounds','Private chats, groups, channels, calls and sound behavior')+'<div class="settings-card">'+row('Private chats','Direct conversation alerts',toggle('private_notifications',p.private_notifications))+row('Groups','Group conversation alerts',toggle('group_notifications',p.group_notifications))+row('Channels','Channel alerts when supported',toggle('channel_notifications',p.channel_notifications))+row('Message previews','Show message text in notifications',toggle('message_preview',p.message_preview))+row('Call notifications','Incoming voice and video call alerts',toggle('calls_enabled',p.calls_enabled))+row('Notification sound','Play notification sounds',toggle('notification_sound',p.notification_sound))+row('Vibration','Use device vibration when supported',toggle('notification_vibrate',p.notification_vibrate))+row('In-app sounds','Play sounds while using VexaChat',toggle('in_chat_sounds',p.in_chat_sounds))+row('Browser permission','Allow this device to display notifications','<button class="secondary" id="requestNotify">Enable</button>')+'</div><div class="settings-card"><button class="settings-action" id="resetNotifications"><b>Reset notification settings</b><span>Restore notification and sound preferences</span></button></div>'}
 function chats(){return heading('Chat Settings','Composition, media playback and message behavior')+'<div class="settings-card">'+row('Enter to send','Enter sends a message instead of a new line',toggle('enter_to_send',p.enter_to_send))+row('Link previews','Generate previews for supported links',toggle('link_previews',p.link_previews))+row('In-chat sounds','Play message interaction sounds',toggle('in_chat_sounds',p.in_chat_sounds))+row('Autoplay GIFs','Automatically play received GIF media',toggle('autoplay_gifs',p.autoplay_gifs))+row('Autoplay videos','Automatically play received videos',toggle('autoplay_videos',p.autoplay_videos))+row('Save received media','Allow supported media to be saved to this device',toggle('save_media',p.save_media))+row('Animations','Use chat transitions and motion',toggle('animations',p.animations))+'</div>'}
 function appearance(){return heading('Appearance','Theme, density and messenger geometry')+'<div class="settings-card">'+row('Theme','Application color scheme',select('appearance',['system','dark','light'],p.appearance))+row('Chat density','Conversation and list spacing',select('density',['comfortable','compact'],p.density))+row('Animations','Use transitions and motion',toggle('animations',p.animations))+'</div><div class="settings-card"><div class="settings-info-row"><b>Responsive layout</b><span>VexaChat uses a Telegram-style mobile list, top chat header, message canvas, composer and desktop two-pane geometry.</span></div></div>'}
 function foldersView(){const fs=folders();const builtin='<div class="folder-manage-list"><div class="folder-manage-row"><b>All</b><span>Every active conversation</span></div><div class="folder-manage-row"><b>Personal</b><span>Direct conversations</span></div><div class="folder-manage-row"><b>Work</b><span>Group conversations tagged as work by the current filter</span></div><div class="folder-manage-row"><b>Groups</b><span>Group conversations</span></div><div class="folder-manage-row"><b>Channels</b><span>Reserved for channel support when enabled by the backend</span></div></div>';const custom=fs.map(f=>'<div class="folder-manage-row custom"><div><b>'+esc(f.name)+'</b><span>'+esc(f.filter==='unread'?'Unread conversations':f.filter==='pinned'?'Pinned conversations':f.filter==='groups'?'Group conversations':'Personal conversations')+'</span></div><div class="folder-actions"><button class="secondary" data-folder-rename="'+esc(f.id)+'">Rename</button><button class="danger" data-folder-delete="'+esc(f.id)+'">Delete</button></div></div>').join('');return heading('Chat Folders','Create local folders that immediately filter your conversation list')+'<div class="settings-card">'+builtin+'</div><div class="settings-card"><div class="settings-section-title"><b>Custom folders</b><button class="primary" id="createFolder">＋ New folder</button></div>'+(custom||'<div class="settings-empty">No custom folders yet.</div>')+'</div><div class="settings-note">Custom folders are stored on this device because the current VexaAccount API does not expose a server-side folder endpoint.</div>'}
 function devices(){return heading('Devices','Signed-in VexaChat sessions')+'<div class="settings-card settings-device-card"><div class="device-icon">▣</div><div><b>This device</b><span>Current VexaChat web/app session</span><small>Authentication is managed by your VexaAccount access token.</small></div><i>Active</i></div><div class="settings-card"><div class="settings-info-row"><b>Remote sessions</b><span>Remote session listing/revocation is not exposed by the current backend.</span></div></div>'}
 function data(){const size=bytesOfStorage();let drafts=0;try{drafts=Object.keys(JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')).length}catch{}return heading('Data & Storage','Automatic media, streaming and local storage')+'<div class="settings-card"><div class="storage-meter"><b>Local app storage</b><strong>'+fmtBytes(size)+'</strong></div>'+row('Data saver','Reduce automatic media and network usage',toggle('data_saver',p.data_saver))+row('Mobile data','Automatic media on mobile data',toggle('auto_download_mobile',p.auto_download_mobile))+row('Wi-Fi','Automatic media on Wi-Fi',toggle('auto_download_wifi',p.auto_download_wifi))+row('Roaming','Automatic media while roaming',toggle('auto_download_roaming',p.auto_download_roaming))+row('Streaming','Start supported media before full download',toggle('streaming',p.streaming))+row('Use less data for calls','Reduce call data usage when possible',toggle('use_less_data_calls',p.use_less_data_calls))+row('Drafts','Saved message drafts','<span class="settings-value">'+drafts+'</span>')+row('Clear drafts','Remove local drafts','<button class="secondary" id="clearDrafts">Clear</button>')+'</div><div class="settings-note">Local cleanup does not delete server messages, contacts or your VexaAccount.</div>'}
 function language(){return heading('Language','Choose the VexaChat interface language')+'<div class="settings-card">'+row('Application language','Interface language',select('language',['English','myanmar'],p.language==='မြန်မာ'?'myanmar':p.language))+'</div>'}
 function premium(){return heading('VexaChat Premium','Premium-ready account area')+'<div class="settings-card settings-premium-card"><div class="premium-mark">✦</div><div><b>Premium services are not connected yet</b><p>VexaChat does not invent subscription status or take payment without a real VexaAccount billing/entitlement API. The UI is ready to host those real entitlements when the backend exposes them.</p><button class="secondary" id="premiumDetails">View available capabilities</button></div></div><div class="settings-card"><div class="settings-info-row"><b>Currently available</b><span>Messaging, groups, reactions, attachments, drafts, folders, contacts, call history and WebRTC call controls.</span></div></div>'}
 function help(){return heading('Help & FAQ','Expandable answers without leaving VexaChat')+'<div class="settings-card faq-list">'+[['login','How does VexaChat sign-in work?','VexaChat sends authentication requests to the VexaAccount API and keeps the signed-in experience inside VexaChat.'],['privacy','Where are privacy settings stored?','Read receipts, last seen, profile photo and call visibility use the VexaChat privacy API.'],['calls','Can I make calls?','Voice and video call controls, incoming-call handling and call history are available when the browser/device provides the required WebRTC capabilities.'],['folders','How do custom folders work?','Custom folders are stored locally on this device and filter chats by unread, pinned, groups or personal conversations.'],['data','Will clearing local data delete my messages?','No. Local cleanup only removes drafts or preferences from this device. Server-side conversations remain untouched.']].map(x=>'<button class="faq-item" data-faq="'+x[0]+'"><b>'+esc(x[1])+'</b><span>'+esc(x[2])+'</span></button>').join('')+'</div><div class="settings-card"><button class="settings-action" id="reportProblem"><b>Report a problem</b><span>Copy a support-ready diagnostic summary</span></button></div>'}
 function bind(){
  ['read_receipts','enter_to_send','link_previews','autoplay_media','autoplay_gifs','autoplay_videos','animations','data_saver','notification_sound','notification_vibrate','save_media','private_notifications','group_notifications','channel_notifications','in_chat_sounds','auto_download_mobile','auto_download_wifi','auto_download_roaming','streaming','use_less_data_calls'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',async e=>{p[id]=e.target.checked;save(p);applyPreferences(p);if(id==='read_receipts')await savePrivacy()}));
  ['desktop_notifications','message_preview','calls_enabled'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',async e=>{p[id]=e.target.checked;save(p);await notifySave();render() }));
  ['last_seen','profile_photo','calls_from'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',async e=>{p[id]=e.target.value;save(p);await savePrivacy()}));
  ['appearance','density'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',e=>{p[id]=e.target.value;save(p);applyPreferences(p)}));
  document.querySelector('#language')?.addEventListener('change',e=>{p.language=e.target.value==='myanmar'?'မြန်မာ':e.target.value;save(p);ctx.notify('Language preference saved')});
  document.querySelector('#editProfile')?.addEventListener('click',()=>{document.querySelector('#modal')?.remove();ctx.profile()});
  document.querySelector('#securitySettings')?.addEventListener('click',()=>{document.querySelector('#modal')?.remove();ctx.accountSecurity?.()});
  document.querySelector('#signOut')?.addEventListener('click',ctx.logout);
  document.querySelector('#resetNotifications')?.addEventListener('click',()=>{['private_notifications','group_notifications','channel_notifications','message_preview','calls_enabled','notification_sound','notification_vibrate','in_chat_sounds'].forEach(k=>p[k]=defaults[k]);save(p);ctx.notify('Notification settings reset');render()});document.querySelector('#requestNotify')?.addEventListener('click',async()=>{if(!('Notification' in window))return ctx.notify('Notifications are not supported on this device');const permission=await Notification.requestPermission();ctx.notify(permission==='granted'?'Notifications enabled':'Notifications not enabled')});
  document.querySelector('#clearDrafts')?.addEventListener('click',()=>{localStorage.removeItem(DRAFT_KEY);ctx.notify('All local drafts cleared');render()});
  document.querySelector('#clearPrefs')?.addEventListener('click',()=>{localStorage.removeItem(KEY);Object.assign(p,defaults);save(p);applyPreferences(p);ctx.notify('Preferences reset');render()});
  document.querySelector('#createFolder')?.addEventListener('click',()=>{const name=prompt('Folder name');if(!name?.trim())return;const fs=folders();if(fs.some(f=>f.name.toLowerCase()===name.trim().toLowerCase()))return ctx.notify('A folder with that name already exists');const filter=prompt('Folder rule: unread, pinned, groups, or personal','unread');if(!['unread','pinned','groups','personal'].includes(String(filter).toLowerCase()))return ctx.notify('Folder rule not supported');fs.push({id:'custom_'+Date.now(),name:name.trim().slice(0,32),filter:String(filter).toLowerCase()});saveFolders(fs);ctx.state.customFolders=fs;ctx.state.folder=fs.at(-1).id;ctx.notify('Folder created');render();ctx.state.folder=fs.at(-1).id;window.dispatchEvent(new CustomEvent('vexachat:folders-changed'))});
  document.querySelectorAll('[data-folder-rename]').forEach(b=>b.onclick=()=>{const fs=folders(),f=fs.find(x=>x.id===b.dataset.folderRename);if(!f)return;const name=prompt('New folder name',f.name);if(!name?.trim())return;f.name=name.trim().slice(0,32);saveFolders(fs);ctx.state.customFolders=fs;ctx.notify('Folder renamed');render();window.dispatchEvent(new CustomEvent('vexachat:folders-changed'))});
  document.querySelectorAll('[data-folder-delete]').forEach(b=>b.onclick=()=>{const fs=folders(),id=b.dataset.folderDelete;const next=fs.filter(x=>x.id!==id);saveFolders(next);ctx.state.customFolders=next;if(ctx.state.folder===id)ctx.state.folder='all';ctx.notify('Folder deleted');render();window.dispatchEvent(new CustomEvent('vexachat:folders-changed'))});
  document.querySelectorAll('[data-faq]').forEach(b=>b.onclick=()=>b.classList.toggle('open'));
  document.querySelector('#premiumDetails')?.addEventListener('click',()=>ctx.notify('Premium billing and entitlements require a real account API endpoint; no fake subscription is shown.'));
  document.querySelector('#reportProblem')?.addEventListener('click',()=>{const summary='VexaChat diagnostic: '+navigator.userAgent+' · online='+navigator.onLine+' · language='+navigator.language+' · localStorage='+fmtBytes(bytesOfStorage());if(navigator.clipboard?.writeText)navigator.clipboard.writeText(summary).then(()=>ctx.notify('Diagnostic summary copied')).catch(()=>ctx.notify(summary));else ctx.notify(summary)});
 }
 applyPreferences(p);
 Promise.resolve(ctx.api('/api/chat/privacy/settings')).then(d=>{const s=d.settings||{};if(Object.keys(s).length){Object.assign(p,{read_receipts:s.read_receipts!==0,last_seen:s.last_seen||p.last_seen,profile_photo:s.profile_photo||p.profile_photo,calls_from:s.calls_from||p.calls_from});save(p)}render()}).catch(()=>render());
}
window.VexaChatSettings={open};
})();