(()=>{'use strict';
const KEY='vexachat_preferences_v1';
const defaults={appearance:'system',density:'comfortable',enter_to_send:true,animations:true,link_previews:true,autoplay_media:false,read_receipts:true,last_seen:'everyone',profile_photo:'everyone',calls_from:'contacts',message_preview:true,desktop_notifications:true,language:'English',data_saver:false};
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}};
const save=p=>localStorage.setItem(KEY,JSON.stringify(p));
const applyPreferences=p=>{document.documentElement.dataset.theme=p.appearance;document.documentElement.dataset.density=p.density;document.documentElement.dataset.motion=p.animations?'on':'off'};
applyPreferences(load());
function open(ctx,initialSection){
 const p=load();const ns=ctx.state.settings||{};Object.assign(p,{desktop_notifications:ns.messages_enabled!==0,message_preview:ns.previews_enabled!==0,calls_enabled:ns.calls_enabled!==0});
 let section=['account','privacy','notifications','chats','appearance','folders','devices','data','language','premium','help'].includes(initialSection)?initialSection:'account';
 const sections=[
 ['account','Account','Identity and profile'],['privacy','Privacy & Security','Visibility and calls'],['notifications','Notifications & Sounds','Alerts and previews'],['chats','Chat Settings','Composer and media'],['appearance','Appearance','Theme and density'],['folders','Chat Folders','Organize conversations'],['devices','Devices','Signed-in session'],['data','Data & Storage','Network and media'],['language','Language','Interface language'],['premium','VexaChat Premium','Premium features'],['help','Help & FAQ','Support and answers']
 ];
 const esc=s=>ctx.esc(String(s??''));
 const row=(label,desc,control)=>'<div class="settings-row"><div><strong>'+esc(label)+'</strong><small>'+esc(desc)+'</small></div>'+control+'</div>';
 const toggle=(id,on)=>'<label class="switch"><input id="'+id+'" type="checkbox" '+(on?'checked':'')+'><span></span></label>';
 const select=(id,values,value)=>'<select class="settings-select" id="'+id+'">'+values.map(v=>'<option value="'+v+'" '+(v===value?'selected':'')+'>'+esc(v==='myanmar'?'မြန်မာ':v[0].toUpperCase()+v.slice(1))+'</option>').join('')+'</select>';
 const heading=(t,d)=>'<div class="settings-heading"><h3>'+esc(t)+'</h3><p>'+esc(d)+'</p></div>';
 const icon=x=>({account:'●',privacy:'⌁',notifications:'◉',chats:'▣',appearance:'◐',folders:'▤',devices:'▤',data:'⇅',language:'文',premium:'✦',help:'?'})[x]||'•';
 const notifySave=async()=>{try{ctx.state.settings=(await ctx.api('/api/chat/notifications/settings',{method:'PUT',body:JSON.stringify({messages_enabled:p.desktop_notifications,calls_enabled:p.calls_enabled!==false,previews_enabled:p.message_preview})})).settings;ctx.notify('Notification settings saved')}catch(e){ctx.notify(e.message)}};
 const savePrivacy=async()=>{try{await ctx.api('/api/chat/privacy/settings',{method:'PATCH',body:JSON.stringify({read_receipts:p.read_receipts,last_seen:p.last_seen,profile_photo:p.profile_photo,calls_from:p.calls_from})});ctx.notify('Privacy settings saved')}catch(e){ctx.notify(e.message)}};
 function render(){
  const body={account,privacy,notifications,chats,appearance,folders,devices,data,language,premium,help}[section]();
  ctx.modal('VexaChat Settings','<div class="settings-layout"><nav class="settings-nav">'+sections.map(s=>'<button class="'+(s[0]===section?'active':'')+'" data-setting="'+s[0]+'"><span>'+icon(s[0])+'</span><b>'+esc(s[1])+'</b><small>'+esc(s[2])+'</small></button>').join('')+'</nav><section class="settings-content">'+body+'</section></div>');
  document.querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>{section=b.dataset.setting;render()});bind();
 }
 function account(){
  const m=ctx.state.me||{};const url=m.avatar_url||m.picture||m.avatar||'';
  const avatar=url?'<div class="avatar avatar-image"><img src="'+esc(url)+'" alt="" loading="lazy"><span>'+esc(ctx.initials(m.name||m.email))+'</span></div>':'<div class="avatar">'+esc(ctx.initials(m.name||m.email))+'</div>';
  return heading('Account','Manage the VexaAccount identity used by VexaChat')+'<div class="settings-profile">'+avatar+'<div><strong>'+esc(m.name||'VexaAccount user')+'</strong><small>'+esc(m.email||'')+'</small></div></div><div class="settings-card"><button class="settings-action" id="editProfile"><b>Edit profile</b><span>Display name, bio and profile photo</span></button><button class="settings-action" id="securitySettings"><b>Account security</b><span>Password and two-step verification</span></button><button class="settings-action" id="signOut"><b>Sign out</b><span>End this VexaChat session</span></button></div><div class="settings-note">VexaChat authenticates against the VexaAccount API and keeps the active experience inside VexaChat.</div>';
 }
 function privacy(){return heading('Privacy & Security','Control visibility, read state and incoming calls')+'<div class="settings-card">'+row('Read receipts','Show when messages are read',toggle('read_receipts',p.read_receipts))+row('Last seen','Who can see your online activity',select('last_seen',['everyone','contacts','nobody'],p.last_seen))+row('Profile photo','Who can view your profile photo',select('profile_photo',['everyone','contacts','nobody'],p.profile_photo))+row('Calls','Who can start calls with you',select('calls_from',['everyone','contacts','nobody'],p.calls_from))+'</div><div class="settings-note">These privacy controls are stored on your VexaChat account and applied by the messaging API.</div>'}
 function notifications(){const s=ctx.state.settings||{};return heading('Notifications & Sounds','Choose how VexaChat alerts you')+'<div class="settings-card">'+row('Message notifications','New message alerts',toggle('desktop_notifications',s.messages_enabled!==0))+row('Message previews','Show message text in notifications',toggle('message_preview',s.previews_enabled!==0))+row('Call notifications','Incoming voice and video call alerts',toggle('calls_enabled',s.calls_enabled!==0))+row('Browser permission','Allow this device to display notifications','<button class="secondary" id="requestNotify">Enable</button>')+'</div><div class="settings-note">Browser permission is device-specific. Account notification preferences are synchronized through the VexaChat API.</div>'}
 function chats(){return heading('Chat Settings','Message composition, links and media behavior')+'<div class="settings-card">'+row('Enter to send','Enter sends a message instead of a new line',toggle('enter_to_send',p.enter_to_send))+row('Link previews','Generate previews for supported links',toggle('link_previews',p.link_previews))+row('Autoplay media','Automatically play received media',toggle('autoplay_media',p.autoplay_media))+row('Animations','Use chat transitions and motion',toggle('animations',p.animations))+'</div>'}
 function appearance(){return heading('Appearance','Make VexaChat comfortable on phone and desktop')+'<div class="settings-card">'+row('Theme','Choose the application theme',select('appearance',['system','dark','light'],p.appearance))+row('Density','Adjust conversation and list spacing',select('density',['comfortable','compact'],p.density))+row('Animations','Use transitions and motion',toggle('animations',p.animations))+'</div>'}
 function folders(){return heading('Chat Folders','Organize conversations without leaving VexaChat')+'<div class="settings-card settings-feature-card"><div class="feature-icon">▤</div><div><b>Built-in folders</b><p>All, Personal, Work, Groups and Channels filters are available from the chat list.</p></div><button class="secondary" id="openFolders">Open folders</button></div><div class="settings-card"><div class="settings-info-row"><b>Custom folders</b><span>Server-side custom folder creation is not enabled by the current API.</span></div></div>'}
 function devices(){return heading('Devices','Review the current VexaChat session')+'<div class="settings-card settings-device-card"><div class="device-icon">▣</div><div><b>This device</b><span>Current VexaChat web/app session</span><small>Authentication is managed by your VexaAccount access token.</small></div><i>Active</i></div><div class="settings-card"><div class="settings-info-row"><b>Session management</b><span>VexaChat does not expose a separate device-revocation API in the current backend.</span></div></div>'}
 function data(){return heading('Data & Storage','Control media loading and local application data')+'<div class="settings-card">'+row('Data saver','Reduce automatic media and network usage',toggle('data_saver',p.data_saver))+row('Clear local preferences','Reset VexaChat appearance and behavior settings','<button class="secondary" id="clearPrefs">Reset</button>')+'</div><div class="settings-note">Resetting preferences does not delete messages, contacts or VexaAccount data.</div>'}
 function language(){return heading('Language','Choose the VexaChat interface language')+'<div class="settings-card">'+row('Application language','Interface language',select('language',['English','myanmar'],p.language==='မြန်မာ'?'myanmar':p.language))+ '</div><div class="settings-note">The current interface includes English and Myanmar labels; more translations can be added independently.</div>'}
 function premium(){return heading('VexaChat Premium','Premium area prepared for future account-linked features')+'<div class="settings-card settings-premium-card"><div class="premium-mark">✦</div><div><b>Premium</b><p>No premium subscription endpoint is enabled in the current VexaAccount API, so VexaChat will not display a fake purchase or subscription state.</p></div></div><div class="settings-note">When a real subscription API is added, this page can become the in-app plan, billing and entitlement center.</div>'}
 function help(){return heading('Help & FAQ','Quick answers without leaving VexaChat')+'<div class="settings-card faq-list"><button class="faq-item" data-faq="login"><b>How does VexaChat sign-in work?</b><span>VexaChat sends authentication requests to the VexaAccount API and keeps the session in VexaChat.</span></button><button class="faq-item" data-faq="privacy"><b>Where are privacy settings stored?</b><span>Read receipts, last seen, profile photo and call visibility use the VexaChat privacy API.</span></button><button class="faq-item" data-faq="calls"><b>Can I make calls?</b><span>Voice/video call controls and call history are available; browser/WebRTC support depends on the current call session.</span></button><button class="faq-item" data-faq="folders"><b>How do folders work?</b><span>The current chat list provides built-in Personal, Work, Groups and Channels filters.</span></button></div><div class="settings-card"><button class="settings-action" id="reportProblem"><b>Report a problem</b><span>Copy a support-ready diagnostic summary without leaving VexaChat</span></button></div>'}
 function bind(){
  ['read_receipts','enter_to_send','link_previews','autoplay_media','animations','data_saver'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',async e=>{p[id]=e.target.checked;save(p);applyPreferences(p);if(id==='read_receipts')await savePrivacy()}));
  ['desktop_notifications','message_preview','calls_enabled'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',async e=>{p[id]=e.target.checked;save(p);await notifySave();render()}));
  ['last_seen','profile_photo','calls_from'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',async e=>{p[id]=e.target.value;save(p);await savePrivacy()}));
  ['appearance','density'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',e=>{p[id]=e.target.value;save(p);applyPreferences(p)}));
  document.querySelector('#language')?.addEventListener('change',e=>{p.language=e.target.value==='myanmar'?'မြန်မာ':e.target.value;save(p);ctx.notify('Language preference saved')});
  document.querySelector('#editProfile')?.addEventListener('click',()=>{document.querySelector('#modal')?.remove();ctx.profile()});
  document.querySelector('#securitySettings')?.addEventListener('click',()=>{document.querySelector('#modal')?.remove();ctx.accountSecurity?.()});
  document.querySelector('#signOut')?.addEventListener('click',ctx.logout);
  document.querySelector('#requestNotify')?.addEventListener('click',async()=>{if(!('Notification' in window))return ctx.notify('Notifications are not supported on this device');const permission=await Notification.requestPermission();ctx.notify(permission==='granted'?'Notifications enabled':'Notifications not enabled')});
  document.querySelector('#clearPrefs')?.addEventListener('click',()=>{localStorage.removeItem(KEY);Object.assign(p,defaults);save(p);applyPreferences(p);render()});
  document.querySelector('#openFolders')?.addEventListener('click',()=>{document.querySelector('#modal')?.remove();document.querySelector('[data-folder="all"]')?.click();ctx.notify('Folder filters are ready in the chat list')});
  document.querySelectorAll('[data-faq]').forEach(b=>b.onclick=()=>ctx.notify(b.querySelector('span')?.textContent||''));
  document.querySelector('#reportProblem')?.addEventListener('click',()=>{const summary='VexaChat diagnostic: '+navigator.userAgent+' · online='+navigator.onLine+' · language='+navigator.language; if(navigator.clipboard?.writeText)navigator.clipboard.writeText(summary).then(()=>ctx.notify('Diagnostic summary copied')).catch(()=>ctx.notify(summary));else ctx.notify(summary)});
 }
 applyPreferences(p);
 Promise.resolve(ctx.api('/api/chat/privacy/settings')).then(d=>{const s=d.settings||{};if(Object.keys(s).length){Object.assign(p,{read_receipts:s.read_receipts!==0,last_seen:s.last_seen||p.last_seen,profile_photo:s.profile_photo||p.profile_photo,calls_from:s.calls_from||p.calls_from});save(p)}render()}).catch(()=>render());
}
window.VexaChatSettings={open};
})();