(()=>{
const DEFAULT_API='https://api-vexaaccount.onrender.com';const base=String(window.VEXA_SYSTEM_C_BASE||DEFAULT_API).replace(/\/$/,'');const $=id=>document.getElementById(id);let es=null,paused=false,manualClear=false,latest=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setStatus(text,live=false){$('liveText').textContent=text;$('liveDot').style.background=live?'#34d399':'#fbbf24';$('connectionInfo').textContent=`SSE · ${base.replace(/^https?:\/\//,'')}`}
function filteredEvents(events){const source=$('sourceFilter').value,q=$('search').value.trim().toLowerCase();return events.filter(e=>(source==='all'||e.source===source)&&(!q||JSON.stringify(e).toLowerCase().includes(q)))}
function render(d){latest=d;$('db').textContent=d.database?'HEALTHY':'ERROR';$('dbSub').textContent=d.database?'SQL connectivity verified':'SQL connectivity failed';$('sessions').textContent=d.metrics?.activeSessions??0;$('consents').textContent=`${d.metrics?.activeConsents??0} consents`;$('apiRate').textContent=d.metrics?.apiEventsMinute??0;$('apiSuccess').textContent=`${d.metrics?.apiSuccessRate??100}% success`;$('failures5').textContent=d.metrics?.failuresWindow??0;$('security5').textContent=`${d.metrics?.securityEventsWindow??0} security events`;$('apiLatency').textContent=`${d.metrics?.apiLatencyMs??0} ms`;$('snapshotLatency').textContent=`Snapshot ${d.latencyMs??0} ms`;$('dbConnections').textContent=d.metrics?.dbConnections??0;$('dbRunning').textContent=`${d.metrics?.dbRunning??0} running`;$('dbQuestions').textContent=d.metrics?.dbQuestions??0;$('dbCommits').textContent=d.metrics?.dbCommits??0;$('dbRollbacks').textContent=d.metrics?.dbRollbacks??0;$('dbRunning2').textContent=d.metrics?.dbRunning??0;$('updated').textContent=new Date(d.generatedAt).toLocaleTimeString();
$('apps').innerHTML=(d.applications||[]).map(a=>{const age=a.last_used_at?Math.max(0,Math.round((Date.now()-new Date(a.last_used_at))/1000))+' sec ago':'no runtime event';const state=a.status==='active'&&a.active?'active':a.status==='maintenance'?'degraded':'inactive';const apiState=a.status==='active'?'HEALTHY':a.status==='maintenance'?'DEGRADED':'OFFLINE';return `<div class="appRow"><div class="appRowTop"><b>● ${esc(a.display_name)}</b><span class="badge ${state}">${esc(a.status||'unknown').toUpperCase()}</span></div><div class="appMeta"><span>SSO ${a.active?'CONNECTED':'NOT ACTIVE'}</span><span>API ${apiState}</span><span>Sessions ${esc(a.activeSessions)}</span></div><div class="appMeta"><span>Last event ${esc(age)}</span><span>Environment ${esc(a.environment||'unknown')}</span><span>Client ${esc(a.client_id)}</span></div></div>`}).join('')||'<p class="muted">No registered applications found.</p>';
const events=filteredEvents(d.events||[]);$('eventCount').textContent=`${events.length} EVENTS`;if(manualClear)return;$('stream').innerHTML=events.map((e,i)=>{const fail=/fail|reject|error/i.test(e.event_type||'')||Number(e.status_code)>=400;return `<button class="event ${fail?'fail':''}" data-event-index="${i}" type="button"><b>${esc(e.event_type||'event')}</b><div>${esc(e.route||e.client_id||e.resource_type||'VexaAccount')} ${e.method?`· ${esc(e.method)}`:''}</div><small>${esc(e.source||'runtime')} · ${esc(e.created_at)}${e.latency_ms!=null?` · ${esc(e.latency_ms)} ms`:''}</small></button>`}).join('')||'<p class="muted">No matching observable events.</p>';document.querySelectorAll('[data-event-index]').forEach(el=>el.onclick=()=>{$('detail').textContent=JSON.stringify(events[Number(el.dataset.eventIndex)],null,2)})}
async function refresh(){try{const r=await fetch(base+'/api/system-c/snapshot',{credentials:'include',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json());setStatus('LIVE',true)}catch(e){setStatus('SNAPSHOT ERROR');$('detail').textContent=`Snapshot request failed: ${e.message}`}}
function connect(){if(es)es.close();setStatus('CONNECTING');es=new EventSource(base+'/api/system-c/stream',{withCredentials:true});es.addEventListener('snapshot',e=>{try{if(!paused)render(JSON.parse(e.data));setStatus(paused?'PAUSED':'LIVE',!paused)}catch(err){$('detail').textContent='Invalid observatory event received'}});es.addEventListener('observatory-error',e=>{try{$('detail').textContent=JSON.parse(e.data).message}catch{}});es.onerror=()=>{if(es)es.close();setStatus('RECONNECTING');if(!paused)setTimeout(connect,3000)}}
$('pauseBtn').onclick=()=>{paused=!paused;$('pauseBtn').textContent=paused?'▶ Resume stream':'⏸ Pause stream';setStatus(paused?'PAUSED':'LIVE',!paused);if(!paused)refresh()};$('refreshBtn').onclick=()=>{manualClear=false;refresh()};$('clearBtn').onclick=()=>{manualClear=!manualClear;$('clearBtn').textContent=manualClear?'Show live feed':'Clear visible feed';if(!manualClear&&latest)render(latest)};$('sourceFilter').onchange=()=>{manualClear=false;if(latest)render(latest)};$('search').oninput=()=>{manualClear=false;if(latest)render(latest)};connect();
})();