(()=>{'use strict';
const C=window.SystemCScene=window.SystemCScene||{};let canvas,gl,raf=0,last=0,program,buf,particles=[],nodes=[];
const V='attribute vec3 p;attribute float a;uniform float u;void main(){gl_Position=vec4(p,1.0);gl_PointSize=7.0+5.0*a;}' ;
const F='precision mediump float;uniform vec4 c;void main(){vec2 q=gl_PointCoord-vec2(.5);float d=length(q);if(d>.5)discard;float glow=smoothstep(.5,0.0,d);gl_FragColor=vec4(c.rgb,glow*c.a);}' ;
const POS={app:[-.82,.15],sso:[-.42,.45],api:[0,-.05],db:[.42,.42],response:[.82,-.28],security:[-.05,-.62]};
const routeFor=e=>{const t=String(e.event_type||'').toLowerCase(),src=String(e.source||'').toLowerCase();if(src.includes('security')||t.includes('security'))return ['sso','security','api'];if(src.includes('sso')||t.includes('token')||t.includes('session')||t.includes('auth'))return ['app','sso','api','response'];if(t.includes('database')||t.includes('query'))return ['api','db','response'];return ['app','api','db','response']};
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s}
function init(){canvas=document.getElementById('scene3d');if(!canvas)return false;gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false});if(!gl)return false;program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,V));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,F));gl.linkProgram(program);buf=gl.createBuffer();nodes=Object.entries(POS).map(([k,p])=>({k,x:p[0],y:p[1],z:-.2,kind:'node',age:0}));resize();addEventListener('resize',resize);raf=requestAnimationFrame(draw);return true}
function resize(){if(!gl)return;const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);gl.viewport(0,0,canvas.width,canvas.height)}
function add(e){const fail=/fail|error|reject/i.test(String(e.event_type||''))||Number(e.status_code)>=400;const route=routeFor(e),h=fail?0:(String(e.source||'').includes('sso')?.54:String(e.source||'').includes('security')?.12:.73);particles.push({route,segment:0,t:0,x:0,y:0,z:.25,h,fail,age:0,eventId:e.id});if(particles.length>350)particles.splice(0,particles.length-350)}
function advance(p,dt){p.age+=dt;p.t+=dt*(p.fail?.00034:.00055);if(p.t>=1){p.segment++;p.t=0}if(p.segment>=p.route.length-1)p.done=true;const a=POS[p.route[p.segment]],b=POS[p.route[p.segment+1]];const t=p.t,s=t*t*(3-2*t);p.x=a[0]+(b[0]-a[0])*s;p.y=a[1]+(b[1]-a[1])*s+Math.sin(Math.PI*t)*.045;p.z=.35+Math.sin(p.age*.004)*.08}
function color(h,fail){if(fail)return [1,.18,.35,1];const x=Math.abs(h*6-3),r=Math.max(0,1-x),g=Math.max(0,1-Math.abs(h*6-2)),b=Math.max(0,1-Math.abs(h*6-4));return [.25+.75*r,.35+.65*g,.45+.55*b,1]}
function draw(t){if(!gl)return;const dt=Math.min(40,t-last||16);last=t;particles.forEach(p=>advance(p,dt));particles=particles.filter(p=>!p.done&&p.age<14000);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.useProgram(program);const groups=new Map();for(const p of particles){const key=p.fail?'fail':Math.round(p.h*5);if(!groups.has(key,[]))groups.set(key,[]);groups.get(key).push(p)}for(const [key,arr] of groups){const data=[],sizes=[];for(const p of arr){data.push(p.x,p.y,p.z);sizes.push(1)}gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);const lp=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(lp);gl.vertexAttribPointer(lp,3,gl.FLOAT,false,0,0);const ab=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,ab);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(sizes),gl.STREAM_DRAW);const la=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(la);gl.vertexAttribPointer(la,1,gl.FLOAT,false,0,0);const c=color(arr[0].h,key==='fail');gl.uniform4f(gl.getUniformLocation(program,'c'),...c);gl.drawArrays(gl.POINTS,0,arr.length)}raf=requestAnimationFrame(draw)}
C.init=init;C.add=add;C.clear=()=>{particles=[]};C.stop=()=>cancelAnimationFrame(raf);document.readyState==='loading'?addEventListener('DOMContentLoaded',init):init()})();