(()=>{'use strict';
const API=String(window.VEXA_SYSTEM_C_BASE||'https://api-vexaaccount.onrender.com').replace(/\/$/,'');const $=id=>document.getElementById(id);let es=null,paused=false,last=null,particles=[],raf=0,lastFrame=0,seq=0;
const canvas=$('scene'),ctx=canvas.getContext('2d');
const nodes={app:{x:.12,y:.52,z:.2,label:'APPLICATION'},sso:{x:.34,y:.34,z:.55,label:'VEXA SSO'},api:{x:.55,y:.58,z:.72,label:'API CORE'},db:{x:.78,y:.34,z:.45,label:'DATABASE'},return:{x:.9,y:.68,z:.18,label:'RESPONSE'}};
const colors={api:'#9b8cff',sso:'#48d9ff',db:'#55e6a5',security:'#ffc66d',error:'#ff6685'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function resize(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
function setStatus(t,live=false){$('liveText').textContent=t;$('liveDot').style.background=live?'#42f5ad':'#ffc66d'}
function project(n,w,h){return{x:n.x*w+(n.z-.5)*70,y:n.y*h-(n.z-.5)*45}}
function curve(a,b,w,h){const p=project(a,w,h),q=project(b,w,h),mx=(p.x+q.x)/2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.bezierCurveTo(mx,p.y-35,mx,q.y+35,q.x,q.y);ctx.stroke()}
function node(n,w,h,active=false){const p=project(n,w,h),r=active?31:25,g=ctx.createRadialGradient(p.x,p.y,1,p.x,p.y,r*2.2);g.addColorStop(0,'rgba(90,210,255,.32)');g.addColorStop(1,'rgba(20,30,60,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r*2.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=active?'#b9f5ff':'#31527c';ctx.lineWidth=active?2.5:1.2;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#08101f';ctx.beginPath();ctx.arc(p.x,p.y,r-5,0,Math.PI*2);ctx.fill();ctx.fillStyle=active?'#dffbff':'#8da7c8';ctx.font='700 10px Inter,system-ui';ctx.textAlign='center';ctx.fillText(n.label,p.x,p.y+r+18)}
function spawn(e){try{window.SystemCScene&&window.SystemCScene.add&&window.SystemCScene.add(e)}catch{}const fail=/fail|error|reject/i.test(e.event_type||'')||Number(e.status_code)>=400;const type=e.source==='sso-security'?'sso':e.source==='owner-audit'?'security':'api';const from=type==='sso'?nodes.app:type==='security'?nodes.sso:nodes.app;const to=type==='sso'?nodes.sso:type==='security'?nodes.db:nodes.api;particles.push({from,to,t:0,speed:0.0025+Math.random()*.0015,color:fail?colors.error:colors[type],id:++seq,event:e,fail});if(type==='api'&&Math.random()>.45)particles.push({from:nodes.api,to:nodes.db,t:-.25,speed:.0028,color:colors.db,event:e});if(type==='sso')particles.push({from:nodes.sso,to:nodes.api,t:-.35,speed:.0026,color:colors.sso,event:e})}
function particle(p,w,h){p.t+=p.speed;if(p.t>1){p.t=-.15;return}const a=project(p.from,w,h),b=project(p.to,w,h),t=Math.max(0,p.t),x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t-28*Math.sin(Math.PI*t);ctx.shadowBlur=18;ctx.shadowColor=p.color;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(x,y,4.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;for(let i=1;i<5;i++){ctx.globalAlpha=(5-i)/12;ctx.beginPath();ctx.arc(x-(b.x-a.x)*i*.025,y-(b.y-a.y)*i*.025,4-i*.55,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function draw(){const now=performance.now();if(!lastFrame)lastFrame=now;lastFrame=now;const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(w*.5,h*.42,20,w*.5,h*.5,Math.max(w,h)*.7);bg.addColorStop(0,'#101d3c');bg.addColorStop(.5,'#070d1e');bg.addColorStop(1,'#03050d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(83,137,205,.10)';ctx.lineWidth=1;for(let i=0;i<9;i++){ctx.beginPath();ctx.moveTo(0,h*.82+i*18);ctx.lineTo(w,h*.52+i*18);ctx.stroke()}for(let i=0;i<7;i++){ctx.beginPath();ctx.moveTo(w*.12+i*w*.13,h);ctx.lineTo(w*.5+i*w*.08,h*.35);ctx.stroke()}
[['app','sso',colors.sso],['sso','api',colors.api],['api','db',colors.db],['db','return',colors.sso]].forEach(([a,b,c])=>{ctx.strokeStyle=c+'55';ctx.lineWidth=2;curve(nodes[a],nodes[b],w,h);ctx.stroke()});const activeNodes=new Set();particles.forEach(p=>{activeNodes.add(p.from);activeNodes.add(p.to);particle(p,w,h)});Object.entries(nodes).forEach(([k,n])=>node(n,w,h,activeNodes.has(k)));raf=requestAnimationFrame(draw)}draw();
function flowName(e){if(e.source==='sso-security')return 'IDENTITY';if(e.source==='owner-audit')return 'SECURITY';return 'API'}
function render(d){last=d;$('sessions').textContent=d.metrics?.activeSessions??0;$('apiRate').textContent=d.metrics?.apiEventsMinute??0;$('apiLatency').textContent=`${d.metrics?.apiLatencyMs??0} ms`;$('dbConnections').textContent=d.metrics?.dbConnections??0;$('apiSuccess').textContent=`${d.metrics?.apiSuccessRate??100}%`;$('dbQuestions').textContent=d.metrics?.dbQuestions??0;$('dbRunning').textContent=d.metrics?.dbRunning??0;$('security5').textContent=d.metrics?.securityEventsWindow??0;$('updated').textContent=new Date(d.generatedAt).toLocaleTimeString();$('networkHealth').textContent=d.database?'RUNTIME HEALTHY':'RUNTIME DEGRADED';$('healthRing').querySelector('b').textContent=`${d.database?Math.max(0,Math.min(100,Number(d.metrics?.apiSuccessRate??100))):0}%`;
const events=(d.events||[]).slice(0,30);events.slice(0,6).forEach(e=>{if(!particles.some(p=>p.event?.id===e.id))spawn(e)});$('flowPills').innerHTML=events.slice(0,5).map(e=>`<span class="flow-pill ${/fail|error|reject/i.test(e.event_type||'')?'bad':''}"><i></i>${esc(flowName(e))}</span>`).join('');
$('apps').innerHTML=(d.applications||[]).map(a=>{const active=a.status==='active'&&a.active;const degraded=a.status==='maintenance';return `<div class="appNode ${degraded?'degraded':''}"><span class="app-orb"></span><div><b>${esc(a.display_name||a.client_id)}</b><small>SSO ${active?'CONNECTED':'INACTIVE'} · API ${a.status==='active'?'HEALTHY':degraded?'DEGRADED':'OFFLINE'}</small></div><strong>${esc(a.activeSessions??0)}</strong></div>`}).join('')||'<div class="empty">No registered integrations</div>';}
async function refresh(){try{const r=await fetch(API+'/api/system-c/snapshot',{credentials:'include',headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);render(await r.json());setStatus('LIVE',true)}catch(e){setStatus('RECONNECTING')}}
function connect(){if(es)es.close();setStatus('CONNECTING');es=new EventSource(API+'/api/system-c/stream',{withCredentials:true});es.addEventListener('snapshot',ev=>{try{const d=JSON.parse(ev.data);if(!paused){render(d)}setStatus(paused?'PAUSED':'LIVE',!paused)}catch{}});es.onerror=()=>{if(es)es.close();setStatus('RECONNECTING');if(!paused)setTimeout(connect,3000)}}
$('pauseBtn').onclick=()=>{paused=!paused;$('pauseBtn').textContent=paused?'▶':'Ⅱ';setStatus(paused?'PAUSED':'LIVE',!paused);if(!paused)refresh()};$('refreshBtn').onclick=refresh;$('clearBtn').onclick=()=>{particles=[];try{window.SystemCScene&&window.SystemCScene.clear&&window.SystemCScene.clear()}catch{}};connect();refresh();
})();